---
- name: Test pfrest.pfsense.interface_gres_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve Interface GREs
      register: result
      pfrest.pfsense.interface_gres_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].if is defined
          - result.data[0].greif is defined
          - result.data[0].descr is defined
          - result.data[0].add_static_route is defined
          - result.data[0].remote_addr is defined
          - result.data[0].tunnel_local_addr is defined
          - result.data[0].tunnel_remote_addr is defined
          - result.data[0].tunnel_remote_net is defined
          - result.data[0].tunnel_local_addr6 is defined
          - result.data[0].tunnel_remote_addr6 is defined
          - result.data[0].tunnel_remote_net6 is defined
          - result.data[0].id is defined

