---
- name: Test pfrest.pfsense.vpn_wireguard_tunnel module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage WireGuard Tunnel
      register: result
      pfrest.pfsense.vpn_wireguard_tunnel:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - listenport
        enabled: true
        descr: string
        listenport: string
        privatekey: string
        mtu: 9223372036854776000
        addresses:
          - address: string
            mask: 9223372036854776000
            descr: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.enabled is defined
          - result.data.descr is defined
          - result.data.listenport is defined
          - result.data.publickey is defined
          - result.data.privatekey is defined
          - result.data.mtu is defined
          - result.data.addresses is defined
          - result.data.id is defined

