---
- name: Test pfrest.pfsense.system_timezone module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage System Timezone
      register: result
      pfrest.pfsense.system_timezone:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        timezone: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.timezone is defined

