---
- name: Test pfrest.pfsense.system_dns_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read System DNS
      register: result
      pfrest.pfsense.system_dns_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.dnsallowoverride is defined
          - result.data.dnsallowoverride == true
          - result.data.dnslocalhost is defined
          - result.data.dnslocalhost == "local"
          - result.data.dnsserver is defined
          - result.data.dnsserver is sequence

