---
- name: Test pfrest.pfsense.status_openvpn_server_route_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read OpenVPN Server Route Status
      register: result
      pfrest.pfsense.status_openvpn_server_route_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.common_name is defined
          - result.data.common_name == "string"
          - result.data.remote_host is defined
          - result.data.remote_host == "string"
          - result.data.virtual_addr is defined
          - result.data.virtual_addr == "string"
          - result.data.last_time is defined
          - result.data.last_time == "string"
          - result.data.id is defined
          - result.data.id == 0

