---
- name: Test pfrest.pfsense.system_crl_revoked_certificate_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Certificate Revocation List Revoked Certificate
      register: result
      pfrest.pfsense.system_crl_revoked_certificate_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.certref is defined
          - result.data.certref == "string"
          - result.data.serial is defined
          - result.data.serial == "string"
          - result.data.reason is defined
          - result.data.reason == -1
          - result.data.revoke_time is defined
          - result.data.revoke_time == 9223372036854776000
          - result.data.id is defined
          - result.data.id == 0

