---
- name: Test pfrest.pfsense.system_restapi_version_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read REST API Version
      register: result
      pfrest.pfsense.system_restapi_version_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.current_version is defined
          - result.data.current_version == "string"
          - result.data.latest_version is defined
          - result.data.latest_version == "string"
          - result.data.latest_version_release_date is defined
          - result.data.latest_version_release_date == "string"
          - result.data.update_available is defined
          - result.data.update_available == true
          - result.data.available_versions is defined
          - result.data.available_versions is sequence

