---
- name: Test pfrest.pfsense.firewall_schedule_time_range module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage Firewall Schedule Time Range
      register: result
      pfrest.pfsense.firewall_schedule_time_range:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        position:
          - 1
        month:
          - 1
        day:
          - 9223372036854776000
        hour: string
        rangedescr: string
        parent_lookup_fields:
          - name
        name: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.position is defined
          - result.data.month is defined
          - result.data.day is defined
          - result.data.hour is defined
          - result.data.rangedescr is defined
          - result.data.id is defined

