---
- name: Test pfrest.pfsense.services_dns_resolver_domain_override module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage DNS Resolver Domain Override
      register: result
      pfrest.pfsense.services_dns_resolver_domain_override:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        domain: string
        ip: string
        descr: string
        forward_tls_upstream: true
        tls_hostname: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.domain is defined
          - result.data.ip is defined
          - result.data.descr is defined
          - result.data.forward_tls_upstream is defined
          - result.data.tls_hostname is defined
          - result.data.id is defined

