namespace: pfrest
name: pfsense
version: 0.0.6
readme: README.md
authors:
  - Jared Hendrickson (@jaredhendrickson13)
description: >-
  Ansible modules for managing pfSense devices using the pfSense REST API
  package.
license:
  - MIT
repository: https://github.com/pfrest/ansible-collection-pfsense
issues: https://github.com/pfrest/ansible-collection-pfsense/issues
tags:
  - pfsense
  - firewall
  - networking
  - restapi
dependencies: {}
build_ignore:
  - .git
  - .github
  - .gitignore
  - .idea
  - .pylintrc
  - .release-please-manifest.json
  - _build
  - CHANGELOG.md
  - docs
  - extensions
  - generator.yml
  - native.json
  - playbook.yml
  - pyproject.toml
  - release-please-config.json
  - requirements-dev.txt
  - schema.json
  - tests
  - tools
  - venv
  - version.txt
