---
- name: Test pfrest.pfsense.services_acme_account_key_register module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Perform ACME Account Key Register action
      register: result
      pfrest.pfsense.services_acme_account_key_register:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        name: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined

