---
- name: Test pfrest.pfsense.services_bind_zones module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all BIND Zones
      register: result
      pfrest.pfsense.services_bind_zones:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        objects:
          - disabled: true
            name: string
            description: string
            type: master
            view:
              - string
            reversev4: true
            reversev6: true
            rpz: true
            custom: string
            dnssec: true
            backupkeys: true
            slaveip: string
            forwarders:
              - string
            ttl: 9223372036854776000
            baseip: string
            nameserver: string
            mail: string
            serial: 9223372036854776000
            refresh: string
            retry: string
            expire: string
            minimum: string
            enable_updatepolicy: true
            updatepolicy: string
            allowupdate:
              - string
            allowtransfer:
              - string
            allowquery:
              - string
            regdhcpstatic: true
            customzonerecords: string
            records:
              - name: string
                type: A
                rdata: string
                priority: 9223372036854776000

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

