---
- name: Test pfrest.pfsense.services_ntp_time_server module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage NTP Time Server
      register: result
      pfrest.pfsense.services_ntp_time_server:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        timeserver: string
        type: server
        prefer: true
        noselect: true

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.timeserver is defined
          - result.data.type is defined
          - result.data.prefer is defined
          - result.data.noselect is defined
          - result.data.id is defined

