---
- name: Test pfrest.pfsense.services_freeradius_client_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Free RADIUS Client
      register: result
      pfrest.pfsense.services_freeradius_client_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.addr is defined
          - result.data.addr == "string"
          - result.data.ip_version is defined
          - result.data.ip_version == "ipaddr"
          - result.data.description is defined
          - result.data.description == "string"
          - result.data.shortname is defined
          - result.data.shortname == "string"
          - result.data.secret is defined
          - result.data.secret == "string"
          - result.data.proto is defined
          - result.data.proto == "udp"
          - result.data.nastype is defined
          - result.data.nastype == "cisco"
          - result.data.msgauth is defined
          - result.data.msgauth == true
          - result.data.maxconn is defined
          - result.data.maxconn == 9223372036854776000
          - result.data.naslogin is defined
          - result.data.naslogin == "string"
          - result.data.naspassword is defined
          - result.data.naspassword == "string"
          - result.data.id is defined
          - result.data.id == 0

