---
- name: Test pfrest.pfsense.services_haproxy_backend_acl_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read HAProxy Backend Access Control List
      register: result
      pfrest.pfsense.services_haproxy_backend_acl_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.name == "string"
          - result.data.expression is defined
          - result.data.expression == "host_starts_with"
          - result.data.value is defined
          - result.data.value == "string"
          - result.data.casesensitive is defined
          - result.data.casesensitive == true
          - result.data.not is defined
          - result.data.not == true
          - result.data.id is defined
          - result.data.id == 0

