---
- name: Test pfrest.pfsense.vpn_ipsec_phase1_encryptions_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve IPsec Phase 1 Encryptions
      register: result
      pfrest.pfsense.vpn_ipsec_phase1_encryptions_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].encryption_algorithm_name is defined
          - result.data[0].encryption_algorithm_keylen is defined
          - result.data[0].hash_algorithm is defined
          - result.data[0].dhgroup is defined
          - result.data[0].prf_algorithm is defined
          - result.data[0].parent_id is defined
          - result.data[0].id is defined

