---
- name: Test pfrest.pfsense.services_freeradius_interface_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Free RADIUS Interface
      register: result
      pfrest.pfsense.services_freeradius_interface_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.addr is defined
          - result.data.addr == "string"
          - result.data.port is defined
          - result.data.port == "string"
          - result.data.type is defined
          - result.data.type == "auth"
          - result.data.ip_version is defined
          - result.data.ip_version == "ipaddr"
          - result.data.description is defined
          - result.data.description == "string"
          - result.data.id is defined
          - result.data.id == 0

