---
- name: Test pfrest.pfsense.vpn_ipsec_phase2_encryption module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage IPsec Phase 2 Encryption
      register: result
      pfrest.pfsense.vpn_ipsec_phase2_encryption:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        name: aes
        keylen: 9223372036854776000
        parent_lookup_query:
          id: 0
    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.keylen is defined
          - result.data.parent_id is defined
          - result.data.id is defined

