---
- name: Test pfrest.pfsense.services_acme_certificate_action module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage ACME Certificate Action
      register: result
      pfrest.pfsense.services_acme_certificate_action:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        status: active
        command: string
        method: shellcommand
        parent_lookup_query:
          name: string
    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.status is defined
          - result.data.command is defined
          - result.data.method is defined
          - result.data.parent_id is defined
          - result.data.id is defined

