---
- name: Test pfrest.pfsense.firewall_nat_outbound_mappings_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve Outbound NAT Mappings
      register: result
      pfrest.pfsense.firewall_nat_outbound_mappings_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].interface is defined
          - result.data[0].protocol is defined
          - result.data[0].disabled is defined
          - result.data[0].nonat is defined
          - result.data[0].nosync is defined
          - result.data[0].source is defined
          - result.data[0].source_port is defined
          - result.data[0].destination is defined
          - result.data[0].destination_port is defined
          - result.data[0].target is defined
          - result.data[0].target_subnet is defined
          - result.data[0].nat_port is defined
          - result.data[0].static_nat_port is defined
          - result.data[0].poolopts is defined
          - result.data[0].source_hash_key is defined
          - result.data[0].descr is defined
          - result.data[0].id is defined

