---
driver:
  name: docker
platforms:
  - name: pfrest-mock
    image: ghcr.io/pfrest/mock-api
    pre_build_image: true
    override_command: false
    published_ports:
      - "0.0.0.0:15070:5000"
    volumes:
      - "${MOLECULE_SCENARIO_DIRECTORY}/mocks:/mocks:ro"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - destroy
