---
- name: Test pfrest.pfsense.system_restapi_access_list module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all REST API Access List Entries
      register: result
      pfrest.pfsense.system_restapi_access_list:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        objects:
          - type: allow
            weight: 9223372036854776000
            network: string
            users:
              - string
            sched: string
            descr: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

