---
- name: Test pfrest.pfsense.diagnostics_config_history_revision_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Configuration History Entry
      register: result
      pfrest.pfsense.diagnostics_config_history_revision_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.time is defined
          - result.data.time == 9223372036854776000
          - result.data.description is defined
          - result.data.description == "string"
          - result.data.version is defined
          - result.data.version == "string"
          - result.data.filesize is defined
          - result.data.filesize == 9223372036854776000
          - result.data.id is defined
          - result.data.id == 0

