---
- name: Test pfrest.pfsense.services_freeradius_users module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all Free RADIUS Users
      register: result
      pfrest.pfsense.services_freeradius_users:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        objects:
          - username: string
            password: string
            password_encryption: Cleartext-Password
            motp_enable: true
            motp_authmethod: motp
            motp_secret: string
            motp_pin: string
            motp_offset: 9223372036854776000
            description: string
            framed_ip_address: string
            framed_ip_netmask: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

