---
- name: Test pfrest.pfsense.services_dns_resolver_access_list_network_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read DNS Resolver Access List Network
      register: result
      pfrest.pfsense.services_dns_resolver_access_list_network_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.network is defined
          - result.data.network == "string"
          - result.data.mask is defined
          - result.data.mask == 9223372036854776000
          - result.data.description is defined
          - result.data.description == "string"
          - result.data.parent_id is defined
          - result.data.id is defined
          - result.data.id == 0

