---
- name: Test pfrest.pfsense.system_hostname_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read System Hostname
      register: result
      pfrest.pfsense.system_hostname_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.hostname is defined
          - result.data.hostname == "string"
          - result.data.domain is defined
          - result.data.domain == "string"

