---
- name: Test pfrest.pfsense.services_acme_certificate_action_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read ACME Certificate Action
      register: result
      pfrest.pfsense.services_acme_certificate_action_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.status is defined
          - result.data.status == "active"
          - result.data.command is defined
          - result.data.command == "string"
          - result.data.method is defined
          - result.data.method == "shellcommand"
          - result.data.id is defined
          - result.data.id == 0

