---
- name: Test pfrest.pfsense.vpn_wireguard_tunnel_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read WireGuard Tunnel
      register: result
      pfrest.pfsense.vpn_wireguard_tunnel_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.name == "string"
          - result.data.enabled is defined
          - result.data.enabled == true
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.listenport is defined
          - result.data.listenport == "string"
          - result.data.publickey is defined
          - result.data.publickey == "string"
          - result.data.privatekey is defined
          - result.data.privatekey == "string"
          - result.data.mtu is defined
          - result.data.mtu == 9223372036854776000
          - result.data.addresses is defined
          - result.data.addresses is sequence
          - result.data.id is defined
          - result.data.id == 0

