---
- name: Test pfrest.pfsense.services_bind_sync_settings_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read BIND Sync Settings
      register: result
      pfrest.pfsense.services_bind_sync_settings_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.synconchanges is defined
          - result.data.synconchanges == "disabled"
          - result.data.synctimeout is defined
          - result.data.synctimeout == 30
          - result.data.masterip is defined
          - result.data.masterip == "string"

