---
- name: Test pfrest.pfsense.system_certificate_authority_generate module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Perform Certificate Authority (Generated) action
      register: result
      pfrest.pfsense.system_certificate_authority_generate:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        descr: string
        keytype: RSA
        digest_alg: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined

