---
- name: Test pfrest.pfsense.services_dns_resolver_domain_override_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read DNS Resolver Domain Override
      register: result
      pfrest.pfsense.services_dns_resolver_domain_override_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.domain is defined
          - result.data.domain == "string"
          - result.data.ip is defined
          - result.data.ip == "string"
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.forward_tls_upstream is defined
          - result.data.forward_tls_upstream == true
          - result.data.tls_hostname is defined
          - result.data.tls_hostname == "string"
          - result.data.id is defined
          - result.data.id == 0

