---
- name: Test pfrest.pfsense.diagnostics_ping module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Perform Ping action
      register: result
      pfrest.pfsense.diagnostics_ping:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        host: 127.0.0.1

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined

