---
- name: Test pfrest.pfsense.routing_gateway_group_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Routing Gateway Group
      register: result
      pfrest.pfsense.routing_gateway_group_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.name == "string"
          - result.data.trigger is defined
          - result.data.trigger == "down"
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.ipprotocol is defined
          - result.data.ipprotocol == "string"
          - result.data.priorities is defined
          - result.data.priorities is sequence
          - result.data.id is defined
          - result.data.id == 0

