---
- name: Test pfrest.pfsense.firewall_nat_one_to_one_mapping module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage 1:1 NAT mapping
      register: result
      pfrest.pfsense.firewall_nat_one_to_one_mapping:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        interface: string
        disabled: true
        nobinat: true
        natreflection: enable
        ipprotocol: inet
        external: string
        source: string
        destination: string
        descr: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.interface is defined
          - result.data.disabled is defined
          - result.data.nobinat is defined
          - result.data.natreflection is defined
          - result.data.ipprotocol is defined
          - result.data.external is defined
          - result.data.source is defined
          - result.data.destination is defined
          - result.data.descr is defined
          - result.data.id is defined

