---
- name: Test pfrest.pfsense.system_certificate_authority_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Certificate Authority
      register: result
      pfrest.pfsense.system_certificate_authority_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.refid is defined
          - result.data.refid == "string"
          - result.data.trust is defined
          - result.data.trust == true
          - result.data.randomserial is defined
          - result.data.randomserial == true
          - result.data.serial is defined
          - result.data.serial == 9223372036854776000
          - result.data.crt is defined
          - result.data.crt == "string"
          - result.data.prv is defined
          - result.data.prv == "string"
          - result.data.id is defined
          - result.data.id == 0

