---
- name: Test pfrest.pfsense.services_acme_account_key module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage ACME Account Key
      register: result
      pfrest.pfsense.services_acme_account_key:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - name
        name: string
        descr: string
        email: string
        acmeserver: string
        accountkey: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.descr is defined
          - result.data.email is defined
          - result.data.acmeserver is defined
          - result.data.accountkey is defined
          - result.data.id is defined

