---
- name: Test pfrest.pfsense.services_haproxy_settings module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage HA Proxy Settings
      register: result
      pfrest.pfsense.services_haproxy_settings:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        enable: true
        maxconn: 9223372036854776000
        nbthread: 9223372036854776000
        terminate_on_reload: true
        hard_stop_after: string
        carpdev: string
        localstatsport: string
        localstats_refreshtime: 9223372036854776000
        localstats_sticktable_refreshtime: 9223372036854776000
        remotesyslog: string
        logfacility: kern
        loglevel: emerg
        log_send_hostname: string
        dns_resolvers:
          - name: string
            server: string
            port: string
        resolver_retries: 9223372036854776000
        resolver_timeoutretry: string
        resolver_holdvalid: string
        email_mailers:
          - name: string
            mailserver: string
            mailserverport: string
        email_level: ''
        email_myhostname: string
        email_from: string
        email_to: string
        sslcompatibilitymode: auto
        ssldefaultdhparam: 9223372036854776000
        advanced: string
        enablesync: true

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.enable is defined
          - result.data.maxconn is defined
          - result.data.nbthread is defined
          - result.data.terminate_on_reload is defined
          - result.data.hard_stop_after is defined
          - result.data.carpdev is defined
          - result.data.localstatsport is defined
          - result.data.localstats_refreshtime is defined
          - result.data.localstats_sticktable_refreshtime is defined
          - result.data.remotesyslog is defined
          - result.data.logfacility is defined
          - result.data.loglevel is defined
          - result.data.log_send_hostname is defined
          - result.data.dns_resolvers is defined
          - result.data.resolver_retries is defined
          - result.data.resolver_timeoutretry is defined
          - result.data.resolver_holdvalid is defined
          - result.data.email_mailers is defined
          - result.data.email_level is defined
          - result.data.email_myhostname is defined
          - result.data.email_from is defined
          - result.data.email_to is defined
          - result.data.sslcompatibilitymode is defined
          - result.data.ssldefaultdhparam is defined
          - result.data.advanced is defined
          - result.data.enablesync is defined

