---
- name: Test pfrest.pfsense.vpn_ipsec_phase2s module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all IPsec Phase 2s
      register: result
      pfrest.pfsense.vpn_ipsec_phase2s:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        objects:
          - ikeid: 9223372036854776000
            descr: string
            disabled: true
            mode: tunnel
            localid_type: string
            localid_address: string
            localid_netbits: 9223372036854776000
            natlocalid_type: string
            natlocalid_address: string
            natlocalid_netbits: 9223372036854776000
            remoteid_type: string
            remoteid_address: string
            remoteid_netbits: 9223372036854776000
            protocol: esp
            encryption_algorithm_option:
              - name: aes
                keylen: 9223372036854776000
            hash_algorithm_option:
              - hmac_sha1
            pfsgroup: 0
            rekey_time: 9223372036854776000
            rand_time: 9223372036854776000
            lifetime: 9223372036854776000
            pinghost: string
            keepalive: true

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

