---
- name: Test pfrest.pfsense.system_notifications_email_settings_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Email Notification Settings
      register: result
      pfrest.pfsense.system_notifications_email_settings_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.disable is defined
          - result.data.disable == true
          - result.data.ipaddress is defined
          - result.data.ipaddress == "string"
          - result.data.port is defined
          - result.data.port == "string"
          - result.data.timeout is defined
          - result.data.timeout == 9223372036854776000
          - result.data.ssl is defined
          - result.data.ssl == true
          - result.data.sslvalidate is defined
          - result.data.sslvalidate == true
          - result.data.fromaddress is defined
          - result.data.fromaddress == "string"
          - result.data.notifyemailaddress is defined
          - result.data.notifyemailaddress == "string"
          - result.data.authentication_mechanism is defined
          - result.data.authentication_mechanism == "PLAIN"
          - result.data.username is defined
          - result.data.username == "string"
          - result.data.password is defined
          - result.data.password == "string"

