---
- name: Test pfrest.pfsense.services_haproxy_files_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve HA Proxy Files
      register: result
      pfrest.pfsense.services_haproxy_files_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].name is defined
          - result.data[0].type is defined
          - result.data[0].content is defined
          - result.data[0].id is defined

