---
- name: Test pfrest.pfsense.firewall_alias module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage Firewall Alias
      register: result
      pfrest.pfsense.firewall_alias:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - name
        name: string
        type: host
        descr: string
        address:
          - string
        detail:
          - string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.type is defined
          - result.data.descr is defined
          - result.data.address is defined
          - result.data.detail is defined
          - result.data.id is defined

