---
- name: Test pfrest.pfsense.services_haproxy_backend_error_file_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read HA Proxy Backend Error File
      register: result
      pfrest.pfsense.services_haproxy_backend_error_file_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.errorcode is defined
          - result.data.errorcode == 9223372036854776000
          - result.data.errorfile is defined
          - result.data.errorfile == "string"
          - result.data.parent_id is defined
          - result.data.id is defined
          - result.data.id == 0

