---
- name: Test pfrest.pfsense.services_haproxy_files module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all HA Proxy Files
      register: result
      pfrest.pfsense.services_haproxy_files:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        objects:
          - name: string
            type: luascript
            content: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

