---
- name: Test pfrest.pfsense.firewall_virtual_ip_apply module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Perform Virtual IP Apply action
      register: result
      pfrest.pfsense.firewall_virtual_ip_apply:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined

