---
- name: Test pfrest.pfsense.interface_lagg_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Interface LAGG
      register: result
      pfrest.pfsense.interface_lagg_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.laggif is defined
          - result.data.laggif == "string"
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.members is defined
          - result.data.members is sequence
          - result.data.proto is defined
          - result.data.proto == "lacp"
          - result.data.lacptimeout is defined
          - result.data.lacptimeout == "slow"
          - result.data.lagghash is defined
          - result.data.lagghash == "l2"
          - result.data.failovermaster is defined
          - result.data.failovermaster == "string"
          - result.data.id is defined
          - result.data.id == 0

