---
- name: Test pfrest.pfsense.system_webgui_settings module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage Web GUI Settings
      register: result
      pfrest.pfsense.system_webgui_settings:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        protocol: http
        port: string
        sslcertref: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.protocol is defined
          - result.data.port is defined
          - result.data.sslcertref is defined

