---
- name: Test pfrest.pfsense.vpn_wireguard_tunnels_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve WireGuard Tunnels
      register: result
      pfrest.pfsense.vpn_wireguard_tunnels_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].name is defined
          - result.data[0].enabled is defined
          - result.data[0].descr is defined
          - result.data[0].listenport is defined
          - result.data[0].publickey is defined
          - result.data[0].privatekey is defined
          - result.data[0].mtu is defined
          - result.data[0].addresses is defined
          - result.data[0].id is defined

