---
- name: Test pfrest.pfsense.routing_gateway module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage Routing Gateway
      register: result
      pfrest.pfsense.routing_gateway:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - name
        name: string
        descr: string
        disabled: true
        ipprotocol: inet
        interface: string
        gateway: string
        monitor_disable: true
        monitor: string
        action_disable: true
        force_down: true
        dpinger_dont_add_static_route: true
        gw_down_kill_states: ''
        nonlocalgateway: true
        weight: 9223372036854776000
        data_payload: 9223372036854776000
        latencylow: 9223372036854776000
        latencyhigh: 9223372036854776000
        losslow: 9223372036854776000
        losshigh: 9223372036854776000
        interval: 9223372036854776000
        loss_interval: 9223372036854776000
        time_period: 9223372036854776000
        alert_interval: 9223372036854776000

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.descr is defined
          - result.data.disabled is defined
          - result.data.ipprotocol is defined
          - result.data.interface is defined
          - result.data.gateway is defined
          - result.data.monitor_disable is defined
          - result.data.monitor is defined
          - result.data.action_disable is defined
          - result.data.force_down is defined
          - result.data.dpinger_dont_add_static_route is defined
          - result.data.gw_down_kill_states is defined
          - result.data.nonlocalgateway is defined
          - result.data.weight is defined
          - result.data.data_payload is defined
          - result.data.latencylow is defined
          - result.data.latencyhigh is defined
          - result.data.losslow is defined
          - result.data.losshigh is defined
          - result.data.interval is defined
          - result.data.loss_interval is defined
          - result.data.time_period is defined
          - result.data.alert_interval is defined
          - result.data.id is defined

