---
- name: Test pfrest.pfsense.system_version_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read System Version
      register: result
      pfrest.pfsense.system_version_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.version is defined
          - result.data.version == "string"
          - result.data.base is defined
          - result.data.base == "string"
          - result.data.patch is defined
          - result.data.patch == "string"
          - result.data.buildtime is defined
          - result.data.buildtime == "string"

