---
- name: Test pfrest.pfsense.services_acme_certificates_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve ACME Certificates
      register: result
      pfrest.pfsense.services_acme_certificates_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].name is defined
          - result.data[0].descr is defined
          - result.data[0].status is defined
          - result.data[0].acmeaccount is defined
          - result.data[0].keylength is defined
          - result.data[0].keypaste is defined
          - result.data[0].preferredchain is defined
          - result.data[0].oscpstaple is defined
          - result.data[0].dnssleep is defined
          - result.data[0].renewafter is defined
          - result.data[0].a_domainlist is defined
          - result.data[0].a_actionlist is defined
          - result.data[0].id is defined

