---
- name: Test pfrest.pfsense.interface_groups module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all Interface Groups
      register: result
      pfrest.pfsense.interface_groups:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        objects:
          - ifname: string
            members:
              - string
            descr: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

