---
- name: Test pfrest.pfsense.services_acme_account_key_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read ACME Account Key
      register: result
      pfrest.pfsense.services_acme_account_key_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.name is defined
          - result.data.name == "string"
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.email is defined
          - result.data.email == "string"
          - result.data.acmeserver is defined
          - result.data.acmeserver == "string"
          - result.data.accountkey is defined
          - result.data.accountkey == "string"
          - result.data.id is defined
          - result.data.id == 0

