---
- name: Test pfrest.pfsense.interface_vlan_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Interface VLAN
      register: result
      pfrest.pfsense.interface_vlan_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.if is defined
          - result.data.if == "string"
          - result.data.tag is defined
          - result.data.tag == 9223372036854776000
          - result.data.vlanif is defined
          - result.data.vlanif == "string"
          - result.data.pcp is defined
          - result.data.pcp == 9223372036854776000
          - result.data.descr is defined
          - result.data.descr == "string"
          - result.data.id is defined
          - result.data.id == 0

