---
- name: Test pfrest.pfsense.services_freeradius_users_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve Free RADIUS Users
      register: result
      pfrest.pfsense.services_freeradius_users_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].username is defined
          - result.data[0].password is defined
          - result.data[0].password_encryption is defined
          - result.data[0].motp_enable is defined
          - result.data[0].motp_authmethod is defined
          - result.data[0].motp_secret is defined
          - result.data[0].motp_pin is defined
          - result.data[0].motp_offset is defined
          - result.data[0].description is defined
          - result.data[0].framed_ip_address is defined
          - result.data[0].framed_ip_netmask is defined
          - result.data[0].id is defined

