---
- name: Test pfrest.pfsense.firewall_states_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve Firewall States
      register: result
      pfrest.pfsense.firewall_states_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].interface is defined
          - result.data[0].protocol is defined
          - result.data[0].direction is defined
          - result.data[0].source is defined
          - result.data[0].destination is defined
          - result.data[0].state is defined
          - result.data[0].age is defined
          - result.data[0].expires_in is defined
          - result.data[0].packets_total is defined
          - result.data[0].packets_in is defined
          - result.data[0].packets_out is defined
          - result.data[0].bytes_total is defined
          - result.data[0].bytes_in is defined
          - result.data[0].bytes_out is defined
          - result.data[0].id is defined

