---
- name: Test pfrest.pfsense.services_dhcp_server_custom_option module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage DHCP Server Custom Option
      register: result
      pfrest.pfsense.services_dhcp_server_custom_option:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - number
        number: 9223372036854776000
        type: text
        value: string
        parent_lookup_query:
          id: 0
    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.number is defined
          - result.data.type is defined
          - result.data.value is defined
          - result.data.parent_id is defined
          - result.data.id is defined

