---
- name: Test pfrest.pfsense.services_dhcp_relay_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read DHCP Relay
      register: result
      pfrest.pfsense.services_dhcp_relay_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.enable is defined
          - result.data.enable == true
          - result.data.interface is defined
          - result.data.interface is sequence
          - result.data.agentoption is defined
          - result.data.agentoption == true
          - result.data.carpstatusvip is defined
          - result.data.carpstatusvip == "string"
          - result.data.server is defined
          - result.data.server is sequence

