---
- name: Test pfrest.pfsense.vpn_openvpn_cso module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage Open VPN Client Specific Override
      register: result
      pfrest.pfsense.vpn_openvpn_cso:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - id
        common_name: string
        disable: true
        block: true
        description: string
        server_list:
          - string
        tunnel_network: string
        tunnel_networkv6: string
        local_network:
          - string
        local_networkv6:
          - string
        remote_network:
          - string
        remote_networkv6:
          - string
        gwredir: true
        push_reset: true
        remove_options:
          - remove_route
        dns_domain: string
        dns_server1: string
        dns_server2: string
        dns_server3: string
        dns_server4: string
        ntp_server1: string
        ntp_server2: string
        netbios_enable: true
        netbios_ntype: 0
        netbios_scope: string
        wins_server1: string
        wins_server2: string
        custom_options:
          - string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.common_name is defined
          - result.data.disable is defined
          - result.data.block is defined
          - result.data.description is defined
          - result.data.server_list is defined
          - result.data.tunnel_network is defined
          - result.data.tunnel_networkv6 is defined
          - result.data.local_network is defined
          - result.data.local_networkv6 is defined
          - result.data.remote_network is defined
          - result.data.remote_networkv6 is defined
          - result.data.gwredir is defined
          - result.data.push_reset is defined
          - result.data.remove_options is defined
          - result.data.dns_domain is defined
          - result.data.dns_server1 is defined
          - result.data.dns_server2 is defined
          - result.data.dns_server3 is defined
          - result.data.dns_server4 is defined
          - result.data.ntp_server1 is defined
          - result.data.ntp_server2 is defined
          - result.data.netbios_enable is defined
          - result.data.netbios_ntype is defined
          - result.data.netbios_scope is defined
          - result.data.wins_server1 is defined
          - result.data.wins_server2 is defined
          - result.data.custom_options is defined
          - result.data.id is defined

