---
- name: Test pfrest.pfsense.user_auth_server module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage authentication server
      register: result
      pfrest.pfsense.user_auth_server:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        state: present
        lookup_fields:
          - name
        type: ldap
        name: string
        host: string
        ldap_port: string
        ldap_urltype: Standard TCP
        ldap_protver: 2
        ldap_timeout: 9223372036854776000
        ldap_caref: string
        ldap_scope: one
        ldap_basedn: string
        ldap_authcn: string
        ldap_extended_enabled: true
        ldap_extended_query: string
        ldap_binddn: string
        ldap_bindpw: string
        ldap_attr_user: string
        ldap_attr_group: string
        ldap_attr_member: string
        ldap_rfc2307: true
        ldap_rfc2307_userdn: true
        ldap_attr_groupobj: string
        ldap_pam_groupdn: string
        ldap_utf8: true
        ldap_nostrip_at: true
        ldap_allow_unauthenticated: true
        radius_secret: string
        radius_auth_port: string
        radius_acct_port: string
        radius_protocol: MSCHAPv2
        radius_timeout: 9223372036854776000
        radius_nasip_attribute: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.refid is defined
          - result.data.type is defined
          - result.data.name is defined
          - result.data.host is defined
          - result.data.ldap_port is defined
          - result.data.ldap_urltype is defined
          - result.data.ldap_protver is defined
          - result.data.ldap_timeout is defined
          - result.data.ldap_caref is defined
          - result.data.ldap_scope is defined
          - result.data.ldap_basedn is defined
          - result.data.ldap_authcn is defined
          - result.data.ldap_extended_enabled is defined
          - result.data.ldap_extended_query is defined
          - result.data.ldap_binddn is defined
          - result.data.ldap_bindpw is defined
          - result.data.ldap_attr_user is defined
          - result.data.ldap_attr_group is defined
          - result.data.ldap_attr_member is defined
          - result.data.ldap_rfc2307 is defined
          - result.data.ldap_rfc2307_userdn is defined
          - result.data.ldap_attr_groupobj is defined
          - result.data.ldap_pam_groupdn is defined
          - result.data.ldap_utf8 is defined
          - result.data.ldap_nostrip_at is defined
          - result.data.ldap_allow_unauthenticated is defined
          - result.data.radius_secret is defined
          - result.data.radius_auth_port is defined
          - result.data.radius_acct_port is defined
          - result.data.radius_protocol is defined
          - result.data.radius_timeout is defined
          - result.data.radius_nasip_attribute is defined
          - result.data.id is defined

