---
- name: Test pfrest.pfsense.services_ntp_time_server_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read NTP Time Server
      register: result
      pfrest.pfsense.services_ntp_time_server_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.timeserver is defined
          - result.data.timeserver == "string"
          - result.data.type is defined
          - result.data.type == "server"
          - result.data.prefer is defined
          - result.data.prefer == true
          - result.data.noselect is defined
          - result.data.noselect == true
          - result.data.id is defined
          - result.data.id == 0

