---
- name: Test pfrest.pfsense.vpn_openvpn_csos_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve Open VPN Client Specific Overrides
      register: result
      pfrest.pfsense.vpn_openvpn_csos_info:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].common_name is defined
          - result.data[0].disable is defined
          - result.data[0].block is defined
          - result.data[0].description is defined
          - result.data[0].server_list is defined
          - result.data[0].tunnel_network is defined
          - result.data[0].tunnel_networkv6 is defined
          - result.data[0].local_network is defined
          - result.data[0].local_networkv6 is defined
          - result.data[0].remote_network is defined
          - result.data[0].remote_networkv6 is defined
          - result.data[0].gwredir is defined
          - result.data[0].push_reset is defined
          - result.data[0].remove_options is defined
          - result.data[0].dns_domain is defined
          - result.data[0].dns_server1 is defined
          - result.data[0].dns_server2 is defined
          - result.data[0].dns_server3 is defined
          - result.data[0].dns_server4 is defined
          - result.data[0].ntp_server1 is defined
          - result.data[0].ntp_server2 is defined
          - result.data[0].netbios_enable is defined
          - result.data[0].netbios_ntype is defined
          - result.data[0].netbios_scope is defined
          - result.data[0].wins_server1 is defined
          - result.data[0].wins_server2 is defined
          - result.data[0].custom_options is defined
          - result.data[0].id is defined

