---
- name: Test pfrest.pfsense.vpn_wireguard_peers module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage all WireGuard Peers
      register: result
      pfrest.pfsense.vpn_wireguard_peers:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        objects:
          - enabled: true
            tun: string
            endpoint: string
            port: string
            descr: string
            persistentkeepalive: 9223372036854776000
            publickey: string
            allowedips:
              - address: string
                mask: 9223372036854776000
                descr: string

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence

