---
- name: Test pfrest.pfsense.routing_gateway_group_priority_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read Routing Gateway Group Priority
      register: result
      pfrest.pfsense.routing_gateway_group_priority_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        lookup_params: {}

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.gateway is defined
          - result.data.gateway == "string"
          - result.data.tier is defined
          - result.data.tier == 9223372036854776000
          - result.data.virtual_ip is defined
          - result.data.virtual_ip == "string"
          - result.data.parent_id is defined
          - result.data.id is defined
          - result.data.id == 0

