---
- name: Test pfrest.pfsense.vpn_openvpn_client_export module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Perform Open VPN Client Export action
      register: result
      pfrest.pfsense.vpn_openvpn_client_export:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false
        type: confzip
        server: 9223372036854776000
        certref: "string"
        username: "string"

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined

