---
- name: Test pfrest.pfsense.status_carp module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Manage CARP
      register: result
      pfrest.pfsense.status_carp:
        api_host: localhost
        api_port: 5000
        api_protocol: http
        validate_certs: false
        enable: true
        maintenance_mode: true

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is mapping
          - result.data.enable is defined
          - result.data.maintenance_mode is defined

