---
- name: Test pfrest.pfsense.status_openvpn_server_connections_info module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve OpenVPN Server Connection Statuses
      register: result
      pfrest.pfsense.status_openvpn_server_connections_info:
        api_host: localhost
        api_port: 15070
        api_protocol: http
        validate_certs: false

    - name: Assert results
      ansible.builtin.assert:
        that:
          - result is defined
          - result is mapping
          - result.code is defined
          - result.code == 200
          - result.response_id is defined
          - result.response_id == "MOCK_SUCCESS"
          - result.msg is defined
          - result.data is defined
          - result.data is sequence
          - 'result.data | length > 0'
          - result.data[0].common_name is defined
          - result.data[0].remote_host is defined
          - result.data[0].virtual_addr is defined
          - result.data[0].virtual_addr6 is defined
          - result.data[0].bytes_recv is defined
          - result.data[0].bytes_sent is defined
          - result.data[0].connect_time is defined
          - result.data[0].connect_time_unix is defined
          - result.data[0].user_name is defined
          - result.data[0].client_id is defined
          - result.data[0].peer_id is defined
          - result.data[0].cipher is defined
          - result.data[0].parent_id is defined
          - result.data[0].id is defined

