#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/firewall/virtual_ip."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: firewall_virtual_ip_info
description:
- Retrieve information about a single Virtual IP.
short_description: Retrieve information about a single Virtual IP.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve Virtual IP
  pfrest.pfsense.firewall_virtual_ip_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Virtual IP data returned by the API.
  type: dict
  returned: always
  contains:
    uniqid:
      description: The unique ID for this virtual IP.
      type: str
      returned: always
    mode:
      description: The virtual IP mode to use for this virtual IP.
      type: str
      returned: always
    interface:
      description: The interface this virtual IP will apply to.
      type: str
      returned: always
    type:
      description: The virtual IP scope type. The `network` option is only applicable
        to the `proxyarp` and `other` virtual IP modes.
      type: str
      returned: always
    subnet:
      description: The address for this virtual IP.
      type: str
      returned: always
    subnet_bits:
      description: The subnet bits for this virtual IP. For `proxyarp` and `other`
        virtual IPs, this value specifies a block of many IP address. For all other
        virtual IP modes, this specifies the subnet mask
      type: int
      returned: always
    descr:
      description: A description for administrative reference
      type: str
      returned: always
    noexpand:
      description: Disable expansion of this entry into IPs on NAT lists (e.g. 192.168.1.0/24
        expands to 256 entries.)
      type: bool
      returned: always
    vhid:
      description: The VHID group that the machines will share.
      type: int
      returned: always
    advbase:
      description: The base frequency that this machine will advertise.
      type: int
      returned: always
    advskew:
      description: The frequency skew that this machine will advertise.
      type: int
      returned: always
    password:
      description: The VHID group password shared by all CARP members.
      type: str
      returned: always
    carp_status:
      description: The current CARP status of this virtual IP. This will display show
        whether this CARP node is the primary or backup peer.
      type: str
      returned: always
    carp_mode:
      description: The CARP mode to use for this virtual IP. Please note this field
        is exclusive to pfSense Plus and has no effect on CE.
      type: str
      returned: always
    carp_peer:
      description: The IP address of the CARP peer. Please note this field is exclusive
        to pfSense Plus and has no effect on CE.
      type: str
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/firewall/virtual_ip."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/firewall/virtual_ip", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
