#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/firewall/traffic_shaper/queue."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: firewall_traffic_shaper_queue
description:
- Manage individual Traffic Shaper Queues.
short_description: Manage individual Traffic Shaper Queues.
requirements:
- pfSense package L(pfSense-pkg-RESTAPI,https://pfrest.org) must be installed on the
  target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: true
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource.
  parent_lookup_query:
    type: dict
    required: true
    description: A dictionary of query parameters used to look up the parent Traffic
      Shaper. This should contain field name/value pairs that uniquely identify the
      parent object this resource is nested under.
  enabled:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the traffic shaper queue.
  name:
    required: true
    type: str
    default: null
    choices: []
    description: The name to assign this traffic shaper queue.
  priority:
    required: false
    type: int
    default: 1
    choices: []
    description: The priority level for this traffic shaper queue.
  qlimit:
    required: true
    type: int
    default: null
    choices: []
    description: The number of packets that can be held in a queue waiting to be transmitted
      by the shaper.
  description:
    required: false
    type: str
    default: ''
    choices: []
    description: A description for this traffic shaper queue.
  default:
    required: false
    type: bool
    default: false
    choices: []
    description: Mark this traffic shaper queue as the default queue.
  red:
    required: false
    type: bool
    default: false
    choices: []
    description: Use the 'Random Early Detection' scheduler option for this traffic
      shaper queue.
  rio:
    required: false
    type: bool
    default: false
    choices: []
    description: Use the 'Random Early Detection In and Out' scheduler option for
      this traffic shaper queue.
  ecn:
    required: false
    type: bool
    default: false
    choices: []
    description: Use the 'Explicit Congestion Notification' scheduler option for this
      traffic shaper queue.
  codel:
    required: false
    type: bool
    default: false
    choices: []
    description: Use the 'Codel Active Queue' scheduler option for this traffic shaper
      queue.
  bandwidthtype:
    required: false
    type: str
    default: Mb
    choices:
    - '%'
    - b
    - Kb
    - Mb
    - Gb
    description: The scale type of the `bandwidth` field's value.
  bandwidth:
    required: false
    type: int
    default: null
    choices: []
    description: The total bandwidth amount allowed by this traffic shaper.
  buckets:
    required: false
    type: int
    default: null
    choices: []
    description: ''
  hogs:
    required: false
    type: int
    default: null
    choices: []
    description: The bandwidth limit per host.
  borrow:
    required: false
    type: bool
    default: false
    choices: []
    description: Allow this queue to borrow from other queues when available.
  upperlimit:
    required: false
    type: bool
    default: false
    choices: []
    description: Allow setting the maximum bandwidth allowed for the queue. Will force
      hard bandwidth limiting.
  upperlimit_m1:
    required: false
    type: str
    default: null
    choices: []
    description: The burst-able bandwidth limit for this traffic shaper queue.
  upperlimit_d:
    required: false
    type: int
    default: null
    choices: []
    description: The duration (in milliseconds) that the burst-able bandwidth limit
      (`upperlimit_m1` is in effect.
  upperlimit_m2:
    required: false
    type: str
    default: null
    choices: []
    description: The normal bandwidth limit for this traffic shaper queue. If `upperlimit_m1`
      is not defined, this limit will always be in effect. If `upperlimit_m1` is defined,
      this limit will take effect after the `upperlimit_d` duration has expired.
  realtime:
    required: false
    type: bool
    default: false
    choices: []
    description: Allow setting the guaranteed bandwidth minimum allotted to the queue.
  realtime_m1:
    required: false
    type: str
    default: null
    choices: []
    description: The guaranteed minimum bandwidth limit for this traffic shaper queue
      during real time.
  realtime_d:
    required: false
    type: int
    default: null
    choices: []
    description: The duration (in milliseconds) that the guaranteed bandwidth limit
      (`realtime_m1`) is in effect.
  realtime_m2:
    required: false
    type: str
    default: null
    choices: []
    description: 'The maximum bandwidth this traffic shaper queue is allowed to use.
      Note: This value should not exceed 30% of parent queue''s maximum bandwidth.'
  linkshare:
    required: false
    type: bool
    default: false
    choices: []
    description: Allow sharing bandwidth from this queue for other queues as long
      as the real time values have been satisfied.
  linkshare_m1:
    required: false
    type: str
    default: null
    choices: []
    description: The initial bandwidth limit for this traffic shaper queue when link
      sharing.
  linkshare_d:
    required: false
    type: int
    default: null
    choices: []
    description: The duration (in milliseconds) that the initial bandwidth limit (`linkshare_m1`)
      is in effect.
  linkshare_m2:
    required: false
    type: str
    default: null
    choices: []
    description: 'The maximum bandwidth this traffic shaper queue is allowed to use.
      Note: This behaves exactly the same as the `bandwidth` field. If this field
      is set, it will override whatever value is current assigned to the `bandwidth`
      field.'
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Create Traffic Shaper Queue
  pfrest.pfsense.firewall_traffic_shaper_queue:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    parent_lookup_query: &id001
      interface: string
    state: present
    name: string
    qlimit: 1
    bandwidth: 1
    upperlimit_m2: string
    realtime_m2: string
    linkshare_m2: string
- name: Delete Traffic Shaper Queue
  pfrest.pfsense.firewall_traffic_shaper_queue:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    parent_lookup_query: *id001
    state: absent
    name: string
    qlimit: 1
    bandwidth: 1
    upperlimit_m2: string
    realtime_m2: string
    linkshare_m2: string

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Traffic Shaper Queue data returned by the API.
  type: dict
  returned: always
  contains:
    interface:
      description: The parent interface this traffic shaper queue a child of. This
        value is automatically determined by the queue's parent and cannot be manually
        set or changed.
      type: str
      returned: always
    enabled:
      description: Enables or disables the traffic shaper queue.
      type: bool
      returned: always
    name:
      description: The name to assign this traffic shaper queue.
      type: str
      returned: always
    priority:
      description: The priority level for this traffic shaper queue.
      type: int
      returned: always
    qlimit:
      description: The number of packets that can be held in a queue waiting to be
        transmitted by the shaper.
      type: int
      returned: always
    description:
      description: A description for this traffic shaper queue.
      type: str
      returned: always
    default:
      description: Mark this traffic shaper queue as the default queue.
      type: bool
      returned: always
    red:
      description: Use the 'Random Early Detection' scheduler option for this traffic
        shaper queue.
      type: bool
      returned: always
    rio:
      description: Use the 'Random Early Detection In and Out' scheduler option for
        this traffic shaper queue.
      type: bool
      returned: always
    ecn:
      description: Use the 'Explicit Congestion Notification' scheduler option for
        this traffic shaper queue.
      type: bool
      returned: always
    codel:
      description: Use the 'Codel Active Queue' scheduler option for this traffic
        shaper queue.
      type: bool
      returned: always
    bandwidthtype:
      description: The scale type of the `bandwidth` field's value.
      type: str
      returned: always
    bandwidth:
      description: The total bandwidth amount allowed by this traffic shaper.
      type: int
      returned: always
    buckets:
      description: The buckets of the object.
      type: int
      returned: always
    hogs:
      description: The bandwidth limit per host.
      type: int
      returned: always
    borrow:
      description: Allow this queue to borrow from other queues when available.
      type: bool
      returned: always
    upperlimit:
      description: Allow setting the maximum bandwidth allowed for the queue. Will
        force hard bandwidth limiting.
      type: bool
      returned: always
    upperlimit_m1:
      description: The burst-able bandwidth limit for this traffic shaper queue.
      type: str
      returned: always
    upperlimit_d:
      description: The duration (in milliseconds) that the burst-able bandwidth limit
        (`upperlimit_m1` is in effect.
      type: int
      returned: always
    upperlimit_m2:
      description: The normal bandwidth limit for this traffic shaper queue. If `upperlimit_m1`
        is not defined, this limit will always be in effect. If `upperlimit_m1` is
        defined, this limit will take effect after the `upperlimit_d` duration has
        expired.
      type: str
      returned: always
    realtime:
      description: Allow setting the guaranteed bandwidth minimum allotted to the
        queue.
      type: bool
      returned: always
    realtime_m1:
      description: The guaranteed minimum bandwidth limit for this traffic shaper
        queue during real time.
      type: str
      returned: always
    realtime_d:
      description: The duration (in milliseconds) that the guaranteed bandwidth limit
        (`realtime_m1`) is in effect.
      type: int
      returned: always
    realtime_m2:
      description: 'The maximum bandwidth this traffic shaper queue is allowed to
        use. Note: This value should not exceed 30% of parent queue''s maximum bandwidth.'
      type: str
      returned: always
    linkshare:
      description: Allow sharing bandwidth from this queue for other queues as long
        as the real time values have been satisfied.
      type: bool
      returned: always
    linkshare_m1:
      description: The initial bandwidth limit for this traffic shaper queue when
        link sharing.
      type: str
      returned: always
    linkshare_d:
      description: The duration (in milliseconds) that the initial bandwidth limit
        (`linkshare_m1`) is in effect.
      type: int
      returned: always
    linkshare_m2:
      description: 'The maximum bandwidth this traffic shaper queue is allowed to
        use. Note: This behaves exactly the same as the `bandwidth` field. If this
        field is set, it will override whatever value is current assigned to the `bandwidth`
        field.'
      type: str
      returned: always
    parent_id:
      description: The ID of the parent Traffic Shaper this resource is nested under.
      type: int
      returned: always

"""


def run_module():
    """Runs this resource module against /api/v2/firewall/traffic_shaper/queue."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "state": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "present",
            "choices": ["present", "absent"],
        },
        "lookup_fields": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "str",
        },
        "parent_lookup_query": {
            "type": "dict",
            "required": True,
            "no_log": False,
        },
        "enabled": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "name": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
            "nullable": False,
        },
        "priority": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 1,
            "nullable": True,
        },
        "qlimit": {
            "type": "int",
            "required": True,
            "no_log": False,
            "default": None,
            "nullable": False,
        },
        "description": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
            "nullable": True,
        },
        "default": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "red": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "rio": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "ecn": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "codel": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "bandwidthtype": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "Mb",
            "choices": ["%", "b", "Kb", "Mb", "Gb"],
            "nullable": True,
        },
        "bandwidth": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "buckets": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "hogs": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "borrow": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "upperlimit": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "upperlimit_m1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "upperlimit_d": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "upperlimit_m2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "realtime": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "realtime_m1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "realtime_d": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "realtime_m2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "linkshare": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "linkshare_m1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "linkshare_d": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "linkshare_m2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/firewall/traffic_shaper/queue", client)
    changed, resp = base_module.set_object_state(
        state=module.params["state"],
        data=module.params,
        lookup_fields=module.params["lookup_fields"],
        parent_lookup_query=module.params.get("parent_lookup_query"),
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
