#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/firewall/traffic_shaper/limiters."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: firewall_traffic_shaper_limiters_info
description:
- Retrieve information about many Traffic Shaper Limiters.
short_description: Retrieve information about many Traffic Shaper Limiters.
requirements:
- pfSense package L(pfSense-pkg-RESTAPI,https://pfrest.org) must be installed on the
  target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  query_params:
    type: dict
    description: Optional query parameters for filtering the results.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve all Traffic Shaper Limiters
  pfrest.pfsense.firewall_traffic_shaper_limiters_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of Traffic Shaper Limiters returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    name:
      description: The unique name for this limiter.
      type: str
      returned: always
    number:
      description: A unique number auto-assigned to this limiter. This is only used
        internally by the system and cannot be manually set or changed.
      type: int
      returned: always
    enabled:
      description: Enables or disables this limiter and its child queues.
      type: bool
      returned: always
    mask:
      description: If `source` or `destination` slots is chosen a dynamic pipe with
        the bandwidth, delay, packet loss and queue size given above will be created
        for each source/destination IP address encountered, respectively. This makes
        it possible to easily specify bandwidth limits per host or subnet.
      type: str
      returned: always
    maskbits:
      description: The IPv4 mask bits to use when determine the scope of the dynamic
        pipe for IPv4 traffic.
      type: int
      returned: always
    maskbitsv6:
      description: The IPv6 mask bits to use when determine the scope of the dynamic
        pipe for IPv4 traffic.
      type: int
      returned: always
    qlimit:
      description: The length of the limiter's queue which the scheduler and AQM are
        responsible for. Set to `null` to assume default.
      type: int
      returned: always
    ecn:
      description: Enable or disable ECN. ECN sets a reserved TCP flag when the queue
        is nearing or exceeding capacity. Not all AQMs or schedulers support this.
      type: bool
      returned: always
    description:
      description: The verbose description for this limiter.
      type: str
      returned: always
    aqm:
      description: The Active Queue Management (AQM) algorithm to use for this limiter.
        AQM is the intelligent drop of network packets inside the limiter, when it
        becomes full or gets close to becoming full, with the goal of reducing network
        congestion.
      type: str
      returned: always
    sched:
      description: The scheduler to use for this limiter. The scheduler manages the
        sequence of network packets in the limiter's queue.
      type: str
      returned: always
    param_codel_target:
      description: The value for the CoDel target parameter.
      type: int
      returned: always
    param_codel_interval:
      description: The value for the CoDel interval parameter.
      type: int
      returned: always
    param_pie_target:
      description: The value for the PIE target parameter.
      type: int
      returned: always
    param_pie_tupdate:
      description: The value for the PIE tupdate parameter.
      type: int
      returned: always
    param_pie_alpha:
      description: The value for the PIE alpha parameter.
      type: int
      returned: always
    param_pie_beta:
      description: The value for the PIE beta parameter.
      type: int
      returned: always
    param_pie_max_burst:
      description: The value for the PIE max_burst parameter.
      type: int
      returned: always
    param_pie_max_ecnth:
      description: The value for the PIE ecnth parameter.
      type: int
      returned: always
    pie_onoff:
      description: Enable or disable turning PIE on and off depending on queue load.
      type: bool
      returned: always
    pie_capdrop:
      description: Enable or disable cap drop adjustment.
      type: bool
      returned: always
    pie_qdelay:
      description: Set queue delay type to timestamps (true) or departure rate estimation
        (false).
      type: bool
      returned: always
    pie_pderand:
      description: Enable or disable drop probability de-randomisation.
      type: bool
      returned: always
    param_red_w_q:
      description: The value for the RED w_q parameter.
      type: int
      returned: always
    param_red_min_th:
      description: The value for the RED min_th parameter.
      type: int
      returned: always
    param_red_max_th:
      description: The value for the RED max_th parameter.
      type: int
      returned: always
    param_red_max_p:
      description: The value for the RED max_p parameter.
      type: int
      returned: always
    param_gred_w_q:
      description: The value for the GRED w_q parameter.
      type: int
      returned: always
    param_gred_min_th:
      description: The value for the GRED min_th parameter.
      type: int
      returned: always
    param_gred_max_th:
      description: The value for the GRED max_th parameter.
      type: int
      returned: always
    param_gred_max_p:
      description: The value for the GRED max_p parameter.
      type: int
      returned: always
    param_fq_codel_target:
      description: The value for the FQ CoDel target parameter.
      type: int
      returned: always
    param_fq_codel_interval:
      description: The value for the FQ CoDel interval parameter.
      type: int
      returned: always
    param_fq_codel_quantum:
      description: The value for the FQ CoDel quantum parameter.
      type: int
      returned: always
    param_fq_codel_limit:
      description: The value for the FQ CoDel limit parameter.
      type: int
      returned: always
    param_fq_codel_flows:
      description: The value for the FQ CoDel flows parameter.
      type: int
      returned: always
    param_fq_pie_target:
      description: The value for the FQ PIE target parameter.
      type: int
      returned: always
    param_fq_pie_tupdate:
      description: The value for the FQ PIE tupdate parameter.
      type: int
      returned: always
    param_fq_pie_alpha:
      description: The value for the FQ PIE alpha parameter.
      type: int
      returned: always
    param_fq_pie_beta:
      description: The value for the FQ PIE beta parameter.
      type: int
      returned: always
    param_fq_pie_max_burst:
      description: The value for the FQ PIE max_burst parameter.
      type: int
      returned: always
    param_fq_pie_max_ecnth:
      description: The value for the FQ PIE ecnth parameter.
      type: int
      returned: always
    param_fq_pie_quantum:
      description: The value for the FQ PIE quantum parameter.
      type: int
      returned: always
    param_fq_pie_limit:
      description: The value for the FQ PIE limit parameter.
      type: int
      returned: always
    param_fq_pie_flows:
      description: The value for the FQ PIE flows parameter.
      type: int
      returned: always
    delay:
      description: The amount of delay (in milliseconds) added to traffic passing
        through this limiter.
      type: int
      returned: always
    plr:
      description: The amount of packet loss (in percentage) added to traffic passing
        through the limiter.
      type: str
      returned: always
    buckets:
      description: The limiter's bucket size (slots).
      type: int
      returned: always
    bandwidth:
      description: The bandwidth profiles for this limiter.
      type: list
      returned: always
      elements: dict
      contains:
        bw:
          description: The amount of bandwidth this profile allows.
          type: int
          returned: always
        bwscale:
          description: The scale factor of the `bw` fields value.
          type: str
          returned: always
        bwsched:
          description: The schedule to assign this bandwidth profile. When this firewall
            schedule is active, this bandwidth profile will be used.
          type: str
          returned: always
    queue:
      description: The child queues for this limiter.
      type: list
      returned: always
      elements: dict
      contains:
        name:
          description: The unique name for this limiter queue.
          type: str
          returned: always
        number:
          description: A unique number auto-assigned to this limiter. This is only
            used internally by the system and cannot be manually set or changed.
          type: int
          returned: always
        enabled:
          description: Enables or disables this limiter queue.
          type: bool
          returned: always
        mask:
          description: If `source` or `destination` slots is chosen a dynamic pipe
            with the bandwidth, delay, packet loss and queue size given above will
            be created for each source/destination IP address encountered, respectively.
            This makes it possible to easily specify bandwidth limits per host or
            subnet.
          type: str
          returned: always
        maskbits:
          description: The IPv4 mask bits to use when determine the scope of the dynamic
            pipe for IPv4 traffic.
          type: int
          returned: always
        maskbitsv6:
          description: The IPv6 mask bits to use when determine the scope of the dynamic
            pipe for IPv4 traffic.
          type: int
          returned: always
        qlimit:
          description: The length of the limiter's queue which the scheduler and AQM
            are responsible for. Set to `null` to assume default.
          type: int
          returned: always
        ecn:
          description: Enable or disable ECN. ECN sets a reserved TCP flag when the
            queue is nearing or exceeding capacity. Not all AQMs or schedulers support
            this.
          type: bool
          returned: always
        description:
          description: The verbose description for this limiter queue.
          type: str
          returned: always
        aqm:
          description: The Active Queue Management (AQM) algorithm to use for this
            queue. AQM is the intelligent drop of network packets inside the queue,
            when it becomes full or gets close to becoming full, with the goal of
            reducing network congestion.
          type: str
          returned: always
        param_codel_target:
          description: The value for the CoDel target parameter.
          type: int
          returned: always
        param_codel_interval:
          description: The value for the CoDel interval parameter.
          type: int
          returned: always
        param_pie_target:
          description: The value for the PIE target parameter.
          type: int
          returned: always
        param_pie_tupdate:
          description: The value for the PIE tupdate parameter.
          type: int
          returned: always
        param_pie_alpha:
          description: The value for the PIE alpha parameter.
          type: int
          returned: always
        param_pie_beta:
          description: The value for the PIE beta parameter.
          type: int
          returned: always
        param_pie_max_burst:
          description: The value for the PIE max_burst parameter.
          type: int
          returned: always
        param_pie_max_ecnth:
          description: The value for the PIE ecnth parameter.
          type: int
          returned: always
        pie_onoff:
          description: Enable or disable turning PIE on and off depending on queue
            load.
          type: bool
          returned: always
        pie_capdrop:
          description: Enable or disable cap drop adjustment.
          type: bool
          returned: always
        pie_qdelay:
          description: Set queue delay type to timestamps (true) or departure rate
            estimation (false).
          type: bool
          returned: always
        pie_pderand:
          description: Enable or disable drop probability de-randomisation.
          type: bool
          returned: always
        param_red_w_q:
          description: The value for the RED w_q parameter.
          type: int
          returned: always
        param_red_min_th:
          description: The value for the RED min_th parameter.
          type: int
          returned: always
        param_red_max_th:
          description: The value for the RED max_th parameter.
          type: int
          returned: always
        param_red_max_p:
          description: The value for the RED max_p parameter.
          type: int
          returned: always
        param_gred_w_q:
          description: The value for the GRED w_q parameter.
          type: int
          returned: always
        param_gred_min_th:
          description: The value for the GRED min_th parameter.
          type: int
          returned: always
        param_gred_max_th:
          description: The value for the GRED max_th parameter.
          type: int
          returned: always
        param_gred_max_p:
          description: The value for the GRED max_p parameter.
          type: int
          returned: always
        weight:
          description: The share of the parent limiter this queue gets.
          type: int
          returned: always
        plr:
          description: The amount of packet loss (in percentage) added to traffic
            passing through this limiter queue.
          type: str
          returned: always
        buckets:
          description: The limiter queue's bucket size (slots).
          type: int
          returned: always

"""


def run_module():
    """Runs this info module against /api/v2/firewall/traffic_shaper/limiters."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "query_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/firewall/traffic_shaper/limiters", client)
    changed = False
    resp = base_module.lookup_objects(lookup_params=module.params["query_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
