#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: interface
description:
- Manage individual Network Interfaces.
short_description: Manage individual Network Interfaces.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  if:
    required: true
    type: str
    default: null
    choices: []
    description: The real interface this configuration will be applied to.
  enable:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable or disable this interface.
  descr:
    required: true
    type: str
    default: null
    choices: []
    description: The descriptive name for this interface.
  spoofmac:
    required: false
    type: str
    default: ''
    choices: []
    description: Assigns (spoofs) the MAC address for this interface instead of using
      the interface's real MAC.
  mtu:
    required: false
    type: int
    default: null
    choices: []
    description: Sets the MTU for this interface. Assumes default MTU if value is
      `null`.
  mss:
    required: false
    type: int
    default: null
    choices: []
    description: Sets the MSS for this interface. Assumes default MSS if value is
      `null`.
  media:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the link speed for this interface. In most situations this can
      be left as the default.
  mediaopt:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the link duplex for this interface. In most situations this
      can be left as the default.
  blockpriv:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable or disable automatically blocking RFC 1918 private networks
      on this interface.
  blockbogons:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable or disable automatically blocking bogon networks on this interface.
  typev4:
    required: true
    type: str
    default: null
    choices:
    - static
    - dhcp
    - none
    description: Selects the IPv4 address type to assign this interface.
  ipaddr:
    required: true
    type: str
    default: null
    choices: []
    description: Sets the IPv4 address to assign to this interface.
  subnet:
    required: true
    type: int
    default: null
    choices: []
    description: Sets the subnet bit count to assign this interface.
  gateway:
    required: false
    type: str
    default: null
    choices: []
    description: Sets the upstream gateway this interface will use. This is only applicable
      for WAN-type interfaces.
  dhcphostname:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the DHCP hostname this interface will advertise via DHCP.
  alias_address:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the value used as a fixed alias IPv4 address by the DHCP client.
  alias_subnet:
    required: false
    type: int
    default: 32
    choices: []
    description: Sets the value used as the fixed alias IPv4 address's subnet bit
      count by the DHCP client.
  dhcprejectfrom:
    required: false
    type: str
    default: []
    choices: []
    description: Sets a list of IPv4 DHCP server addresses to reject DHCP offers for
      on this interface.
  adv_dhcp_config_advanced:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the advanced DHCP settings on this interface.
  adv_dhcp_pt_values:
    required: false
    type: str
    default: SavedCfg
    choices:
    - SavedCfg
    description: Selects the advanced DHCP timing preset.
  adv_dhcp_pt_timeout:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the timeout timing value used when requested DHCP leases
      on this interface.
  adv_dhcp_pt_retry:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the retry timing value used when requested DHCP leases
      on this interface.
  adv_dhcp_pt_select_timeout:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the select timing value used when requested DHCP leases
      on this interface.
  adv_dhcp_pt_reboot:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the reboot timing value used when requested DHCP leases
      on this interface.
  adv_dhcp_pt_backoff_cutoff:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the backoff cutoff timing value used when requested
      DHCP leases on this interface.
  adv_dhcp_pt_initial_interval:
    required: false
    type: int
    default: null
    choices: []
    description: Manually sets the initial interval timing value used when requested
      DHCP leases on this interface.
  adv_dhcp_send_options:
    required: false
    type: str
    default: null
    choices: []
    description: Sets DHCP options to be sent when requesting a DHCP lease for this
      interface.
  adv_dhcp_request_options:
    required: false
    type: str
    default: null
    choices: []
    description: Sets DHCP option 55 values to be sent when requesting a DHCP lease
      for this interface.
  adv_dhcp_required_options:
    required: false
    type: str
    default: null
    choices: []
    description: Sets DHCP options required by the client when requesting a DHCP lease
      for this interface.
  adv_dhcp_option_modifiers:
    required: false
    type: str
    default: null
    choices: []
    description: Sets DHCP option modifiers applied to the obtained DHCP lease.
  adv_dhcp_config_file_override:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables overriding the entire DHCP configuration file
      for this interface.
  adv_dhcp_config_file_override_path:
    required: false
    type: str
    default: null
    choices: []
    description: Sets the local file path of the custom DHCP configuration file.
  typev6:
    required: false
    type: str
    default: null
    choices:
    - staticv6
    - dhcp6
    - slaac
    - 6rd
    - track6
    - 6to4
    - none
    description: Selects the IPv6 address type to assign this interface.
  ipaddrv6:
    required: true
    type: str
    default: null
    choices: []
    description: Sets the IPv6 address to assign to this interface.
  subnetv6:
    required: true
    type: int
    default: null
    choices: []
    description: Sets the subnet bit count to assign this interface.
  gatewayv6:
    required: false
    type: str
    default: null
    choices: []
    description: Sets the upstream IPv6 gateway this interface will use. This is only
      applicable for WAN-type interfaces.
  ipv6usev4iface:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable or disable IPv6 using the IPv4 connectivity link (PPPoE).
  slaacusev4iface:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable or disable IPv6 using the IPv4 connectivity link (PPPoE).
  prefix_6rd:
    required: true
    type: str
    default: null
    choices: []
    description: Sets the 6RD IPv6 prefix assigned by the ISP for this interface.
  gateway_6rd:
    required: true
    type: str
    default: null
    choices: []
    description: Sets the 6RD IPv4 gateway address assigned by the ISP for this interface.
  prefix_6rd_v4plen:
    required: true
    type: int
    default: null
    choices: []
    description: Sets the 6RD IPv4 prefix length. Normally specified by the ISP. A
      value of 0 means embed theentire IPv4 address in the 6RD prefix.
  track6_interface:
    required: true
    type: str
    default: null
    choices: []
    description: Sets the dynamic IPv6 WAN interface to track for configuration.
  track6_prefix_id_hex:
    required: false
    type: str
    default: '0'
    choices: []
    description: Sets the hexadecimal IPv6 prefix ID. This determines the configurable
      network ID based on the dynamic IPv6 connection.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "if": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "enable": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "descr": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "spoofmac": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "mtu": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "mss": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "media": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "mediaopt": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "blockpriv": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "blockbogons": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "typev4": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['static', 'dhcp', 'none'],
        },
        "ipaddr": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "subnet": {
            "type": int,
            "required": True,
            "default": None,
            "choices": [],
        },
        "gateway": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "dhcphostname": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "alias_address": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "alias_subnet": {
            "type": int,
            "required": False,
            "default": 32,
            "choices": [],
        },
        "dhcprejectfrom": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "adv_dhcp_config_advanced": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "adv_dhcp_pt_values": {
            "type": str,
            "required": False,
            "default": 'SavedCfg',
            "choices": ['SavedCfg'],
        },
        "adv_dhcp_pt_timeout": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_pt_retry": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_pt_select_timeout": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_pt_reboot": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_pt_backoff_cutoff": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_pt_initial_interval": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_send_options": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_request_options": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_required_options": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_option_modifiers": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "adv_dhcp_config_file_override": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "adv_dhcp_config_file_override_path": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "typev6": {
            "type": str,
            "required": False,
            "default": None,
            "choices": ['staticv6', 'dhcp6', 'slaac', '6rd', 'track6', '6to4', 'none'],
        },
        "ipaddrv6": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "subnetv6": {
            "type": int,
            "required": True,
            "default": None,
            "choices": [],
        },
        "gatewayv6": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "ipv6usev4iface": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "slaacusev4iface": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "prefix_6rd": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "gateway_6rd": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "prefix_6rd_v4plen": {
            "type": int,
            "required": True,
            "default": None,
            "choices": [],
        },
        "track6_interface": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "track6_prefix_id_hex": {
            "type": str,
            "required": False,
            "default": '0',
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()