#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: interface_lagg
description:
- Manage individual Interface LAGGs.
short_description: Manage individual Interface LAGGs.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  descr:
    required: false
    type: str
    default: ''
    choices: []
    description: A description to help document the purpose of this LAGG interface.
  members:
    required: true
    type: str
    default: null
    choices: []
    description: A list of member interfaces to include in the LAGG.
  proto:
    required: true
    type: str
    default: null
    choices:
    - lacp
    - failover
    - loadbalance
    - roundrobin
    - none
    description: The LAGG protocol to use.
  lacptimeout:
    required: false
    type: str
    default: slow
    choices:
    - slow
    - fast
    description: The LACP timeout mode to use.
  lagghash:
    required: false
    type: str
    default: l2,l3,l4
    choices:
    - l2
    - l3
    - l4
    - l2,l3
    - l2,l4
    - l3,l4
    - l2,l3,l4
    description: The LAGG hash algorithm to use.
  failovermaster:
    required: false
    type: str
    default: auto
    choices: []
    description: The failover master interface to use.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "descr": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "members": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "proto": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['lacp', 'failover', 'loadbalance', 'roundrobin', 'none'],
        },
        "lacptimeout": {
            "type": str,
            "required": False,
            "default": 'slow',
            "choices": ['slow', 'fast'],
        },
        "lagghash": {
            "type": str,
            "required": False,
            "default": 'l2,l3,l4',
            "choices": ['l2', 'l3', 'l4', 'l2,l3', 'l2,l4', 'l3,l4', 'l2,l3,l4'],
        },
        "failovermaster": {
            "type": str,
            "required": False,
            "default": 'auto',
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()