#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: routing_static_route_info
description:
- Retrieve information about a single Static Route.
short_description: Retrieve information about a single Static Route.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Retrieve Static Route
  pfrest.pfsense.routing_static_route_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Static Route data returned by the API.
  type: dict
  returned: always
  contains:
    network:
      description: Sets the destination network for this static route in CIDR notation.
      type: str
      returned: always
    gateway:
      description: Sets which gateway this route applies to.
      type: str
      returned: always
    descr:
      description: Sets a description for administrative reference.
      type: str
      returned: always
    disabled:
      description: Disable this static route.
      type: bool
      returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "default": 'admin',
        },
        "api_password": {
            "type": "str",
            "required": False,
            "default": 'pfsense',
        },
        "api_key": {
            "type": "str",
            "required": False,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule('/api/v2/routing/static_route', client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params['lookup_params'])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get('message', '')
    if 'message' in resp:
        del resp['message']

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if 'code' not in resp or resp['code'] != 200:
        module.fail_json(msg=message, **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()