#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/routing/gateway."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: routing_gateway_info
description:
- Retrieve information about a single Routing Gateway.
short_description: Retrieve information about a single Routing Gateway.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve Routing Gateway
  pfrest.pfsense.routing_gateway_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Routing Gateway data returned by the API.
  type: dict
  returned: always
  contains:
    name:
      description: Sets a name for the gateway.
      type: str
      returned: always
    descr:
      description: Sets a descriptions for the gateway.
      type: str
      returned: always
    disabled:
      description: Disable this gateway.
      type: bool
      returned: always
    ipprotocol:
      description: Sets the Internet Protocol version this gateway uses.
      type: str
      returned: always
    interface:
      description: Sets the interface this gateway will apply to.
      type: str
      returned: always
    gateway:
      description: Sets the IP address of the remote gateway.
      type: str
      returned: always
    monitor_disable:
      description: Disable gateway monitoring for this gateway.
      type: bool
      returned: always
    monitor:
      description: Sets a different IP address to use when monitoring this gateway.
        This is typically only necessary if the gateway IP does not accept ICMP probes.
      type: str
      returned: always
    action_disable:
      description: Disable actions from taking place when gateway events occur. The
        gateway will always be considered up.
      type: bool
      returned: always
    force_down:
      description: Always consider this gateway to be up.
      type: bool
      returned: always
    dpinger_dont_add_static_route:
      description: Prevents gateway monitoring from adding a static route for this
        gateway's monitor IP.
      type: bool
      returned: always
    gw_down_kill_states:
      description: Controls the state killing behavior when this specific gateway
        goes down. Killing states for specific down gateways only affects states created
        by policy routing rules and reply-to. Has no effect if gateway monitoring
        or its action are disabled or if the gateway is forced down. May not have
        any effect on dynamic gateways during a link loss event.
      type: str
      returned: always
    nonlocalgateway:
      description: Allows or disallows gateway IPs that are not a part of the parent
        interface's subnet(s).
      type: bool
      returned: always
    weight:
      description: Sets the weight for this gateway when used in a Gateway Group.
      type: int
      returned: always
    data_payload:
      description: Sets the data payload to send in ICMP packets to gateway monitor
        IP.
      type: int
      returned: always
    latencylow:
      description: Sets the threshold to consider latency as low.
      type: int
      returned: always
    latencyhigh:
      description: Sets the threshold to consider latency as high. This value must
        be greater than `latencylow`.
      type: int
      returned: always
    losslow:
      description: Sets the threshold to consider packet loss as low.
      type: int
      returned: always
    losshigh:
      description: Sets the threshold to consider packet loss as high. This value
        must be greater than `losslow`.
      type: int
      returned: always
    interval:
      description: Sets how often ICMP probes will be sent in milliseconds.
      type: int
      returned: always
    loss_interval:
      description: Sets the time interval in milliseconds before packets are treated
        as lost.
      type: int
      returned: always
    time_period:
      description: Sets the time period in milliseconds over which results are averaged.
      type: int
      returned: always
    alert_interval:
      description: Sets the time interval in milliseconds between checking for an
        alert conditions.
      type: int
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/routing/gateway."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/routing/gateway", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
