#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: services_dhcp_server_address_pool
description:
- Manage individual DHCP Server Address Pools.
short_description: Manage individual DHCP Server Address Pools.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: false
    default: null
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource. If not specified,
      the module will attempt to use the 'id' field if it exists, or all fields marked
      as 'unique' in the schema.
  range_from:
    required: true
    type: str
    default: null
    choices: []
    description: The starting IP address for this address pool. This address must
      be less than or equal to the `range_to` field.
  range_to:
    required: true
    type: str
    default: null
    choices: []
    description: The ending IP address for the this address pool. This address must
      be greater than or equal to the `range_to` field.
  domain:
    required: false
    type: str
    default: ''
    choices: []
    description: The domain to be assigned via DHCP.
  mac_allow:
    required: false
    type: str
    default: []
    choices: []
    description: MAC addresses this DHCP server is allowed to provide leases for.
  mac_deny:
    required: false
    type: str
    default: []
    choices: []
    description: MAC addresses this DHCP server is not allowed to provide leases for.
  domainsearchlist:
    required: false
    type: str
    default: []
    choices: []
    description: The domain search list to provide via DHCP.
  defaultleasetime:
    required: false
    type: int
    default: 7200
    choices: []
    description: The default DHCP lease validity period (in seconds). This is used
      for clients that do not ask for a specific expiration time.
  maxleasetime:
    required: false
    type: int
    default: 86400
    choices: []
    description: The maximum DHCP lease validity period (in seconds) a client can
      request.
  gateway:
    required: false
    type: str
    default: ''
    choices: []
    description: The gateway IPv4 address to provide via DHCP. This is only necessary
      if you are not using the interface's IP as the gateway. Specify `none` for no
      gateway assignment.
  dnsserver:
    required: false
    type: str
    default: []
    choices: []
    description: The DNS servers to provide via DHCP. Leave empty to default to system
      nameservers.
  winsserver:
    required: false
    type: str
    default: []
    choices: []
    description: The WINS servers to provide via DHCP.
  ntpserver:
    required: false
    type: str
    default: []
    choices: []
    description: The NTP servers to provide via DHCP.
  ignorebootp:
    required: false
    type: bool
    default: false
    choices: []
    description: Force this DHCP server to ignore BOOTP queries.
  ignoreclientuids:
    required: false
    type: bool
    default: false
    choices: []
    description: Prevent recording a unique identifier (UID) in client lease data
      if present in the client DHCP request. This option may be useful when a client
      can dual boot using different client identifiers but the same hardware (MAC)
      address. Note that the resulting server behavior violates the official DHCP
      specification.
  denyunknown:
    required: false
    type: str
    default: null
    choices:
    - enabled
    - class
    description: Define how to handle unknown clients requesting DHCP leases. When
      set to `null`, any DHCP client will get an IP address within this scope/range
      on this interface. If set to `enabled`, any DHCP client with a MAC address listed
      in a static mapping on any scope(s)/interface(s) will get an IP address. If
      set to `class`, only MAC addresses listed in static mappings on this interface
      will get an IP address within this scope/range.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Create DHCP Server Address Pool
  pfrest.pfsense.services_dhcp_server_address_pool:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: present
    range_from: example
    range_to: example
- name: Delete DHCP Server Address Pool
  pfrest.pfsense.services_dhcp_server_address_pool:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: absent
    range_from: example
    range_to: example

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The DHCP Server Address Pool data returned by the API.
  type: dict
  returned: always
  contains:
    range_from:
      description: The starting IP address for this address pool. This address must
        be less than or equal to the `range_to` field.
      type: str
      returned: always
    range_to:
      description: The ending IP address for the this address pool. This address must
        be greater than or equal to the `range_to` field.
      type: str
      returned: always
    domain:
      description: The domain to be assigned via DHCP.
      type: str
      returned: always
    mac_allow:
      description: MAC addresses this DHCP server is allowed to provide leases for.
      type: str
      returned: always
    mac_deny:
      description: MAC addresses this DHCP server is not allowed to provide leases
        for.
      type: str
      returned: always
    domainsearchlist:
      description: The domain search list to provide via DHCP.
      type: str
      returned: always
    defaultleasetime:
      description: The default DHCP lease validity period (in seconds). This is used
        for clients that do not ask for a specific expiration time.
      type: int
      returned: always
    maxleasetime:
      description: The maximum DHCP lease validity period (in seconds) a client can
        request.
      type: int
      returned: always
    gateway:
      description: The gateway IPv4 address to provide via DHCP. This is only necessary
        if you are not using the interface's IP as the gateway. Specify `none` for
        no gateway assignment.
      type: str
      returned: always
    dnsserver:
      description: The DNS servers to provide via DHCP. Leave empty to default to
        system nameservers.
      type: str
      returned: always
    winsserver:
      description: The WINS servers to provide via DHCP.
      type: str
      returned: always
    ntpserver:
      description: The NTP servers to provide via DHCP.
      type: str
      returned: always
    ignorebootp:
      description: Force this DHCP server to ignore BOOTP queries.
      type: bool
      returned: always
    ignoreclientuids:
      description: Prevent recording a unique identifier (UID) in client lease data
        if present in the client DHCP request. This option may be useful when a client
        can dual boot using different client identifiers but the same hardware (MAC)
        address. Note that the resulting server behavior violates the official DHCP
        specification.
      type: bool
      returned: always
    denyunknown:
      description: Define how to handle unknown clients requesting DHCP leases. When
        set to `null`, any DHCP client will get an IP address within this scope/range
        on this interface. If set to `enabled`, any DHCP client with a MAC address
        listed in a static mapping on any scope(s)/interface(s) will get an IP address.
        If set to `class`, only MAC addresses listed in static mappings on this interface
        will get an IP address within this scope/range.
      type: str
      returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "state": {
            "type": str,
            "required": False,
            "default": 'present',
            "choices": ['present', 'absent'],
        },
        "lookup_fields": {
            "type": list,
            "required": False,
            "default": None,
            "choices": [],
            "elements": "str",
            "suboptions": {},
        },
        "range_from": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "range_to": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "domain": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "mac_allow": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "mac_deny": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "domainsearchlist": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "defaultleasetime": {
            "type": int,
            "required": False,
            "default": 7200,
            "choices": [],
        },
        "maxleasetime": {
            "type": int,
            "required": False,
            "default": 86400,
            "choices": [],
        },
        "gateway": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "dnsserver": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "winsserver": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "ntpserver": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "ignorebootp": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ignoreclientuids": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "denyunknown": {
            "type": str,
            "required": False,
            "default": None,
            "choices": ['enabled', 'class'],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule(client)
    changed, data = base_module.set_object_state(
        state=module.params['state'],
        data=module.params,
        lookup_fields=module.params['lookup_fields']
    )

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if resp['status'] != 200:
        module.fail_json(msg=resp['message'], **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()