#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: services_bind_settings_info
description:
- Retrieve information about the BIND Settings.
short_description: Retrieve information about the BIND Settings.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Retrieve BIND Settings
  pfrest.pfsense.services_bind_settings_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The BIND Settings data returned by the API.
  type: dict
  returned: always
  contains:
    enable_bind:
      description: Enables the BIND service.
      type: bool
      returned: always
    bind_ip_version:
      description: The IP version to use for the BIND service. Leave empty to use
        both IPv4 and IPv6.
      type: str
      returned: always
    listenon:
      description: The interfaces to listen on for DNS requests.
      type: list
      returned: always
      elements: str
    bind_notify:
      description: Notify slave server after any update on master.
      type: bool
      returned: always
    bind_hide_version:
      description: Hide the BIND version in responses.
      type: bool
      returned: always
    bind_ram_limit:
      description: The maximum amount of RAM to use for the BIND service.
      type: str
      returned: always
    bind_logging:
      description: Enable logging for the BIND service.
      type: bool
      returned: always
    log_severity:
      description: The minimum severity of events to log.
      type: str
      returned: always
    log_options:
      description: The categories to log.
      type: list
      returned: always
      elements: str
    rate_enabled:
      description: Enable rate limiting for the BIND service.
      type: bool
      returned: always
    rate_limit:
      description: The maximum number of queries per second to allow.
      type: int
      returned: always
    log_only:
      description: When rate limiting, only log that the query limit has been exceeded.
        If disabled, the query will be dropped instead.
      type: bool
      returned: always
    bind_forwarder:
      description: Enable forwarding queries to other DNS servers listed below rather
        than this server performing its own recursion.
      type: bool
      returned: always
    bind_forwarder_ips:
      description: The IP addresses of the DNS servers to forward queries to.
      type: list
      returned: always
      elements: str
    bind_dnssec_validation:
      description: Enable DNSSEC validation when BIND is acting as a recursive resolver.
      type: str
      returned: always
    listenport:
      description: 'The TCP and UDP port to listen on for DNS requests. Valid options
        are: a TCP/UDP port number'
      type: str
      returned: always
    controlport:
      description: 'The TCP port to listen on for control requests (localhost only).
        Valid options are: a TCP/UDP port number'
      type: str
      returned: always
    bind_custom_options:
      description: Custom BIND options to include in the configuration file.
      type: str
      returned: always
    bind_global_settings:
      description: Global BIND settings to include in the configuration file.
      type: str
      returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "default": 'admin',
        },
        "api_password": {
            "type": "str",
            "required": False,
            "default": 'pfsense',
        },
        "api_key": {
            "type": "str",
            "required": False,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule('/api/v2/services/bind/settings', client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params['lookup_params'])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get('message', '')
    if 'message' in resp:
        del resp['message']

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if 'code' not in resp or resp['code'] != 200:
        module.fail_json(msg=message, **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()