#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/services/dhcp_relay."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: services_dhcp_relay
description:
- Manage DHCP Relay.
short_description: Manage DHCP Relay.
requirements:
- pfSense-pkg-RESTAPI must be installed on the target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  enable:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the DHCP relay.
  interface:
    required: false
    type: list
    default: []
    choices: []
    description: The downstream interfaces to listen on for DHCP requests.
    elements: str
  agentoption:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables appending the circuit ID (interface number) and
      the agent ID to the DHCP request.
  carpstatusvip:
    required: false
    type: str
    default: none
    choices: []
    description: DHCP Relay will be stopped when the chosen VIP is in BACKUP status,
      and started in MASTER status.
  server:
    required: true
    type: list
    choices: []
    description: The IPv4 addresses of the DHCP server to relay requests to.
    elements: str
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Manage DHCP Relay
  pfrest.pfsense.services_dhcp_relay:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    server:
    - string

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The DHCP Relay data returned by the API.
  type: dict
  returned: always
  contains:
    enable:
      description: Enables or disables the DHCP relay.
      type: bool
      returned: always
    interface:
      description: The downstream interfaces to listen on for DHCP requests.
      type: list
      returned: always
      elements: str
    agentoption:
      description: Enables or disables appending the circuit ID (interface number)
        and the agent ID to the DHCP request.
      type: bool
      returned: always
    carpstatusvip:
      description: DHCP Relay will be stopped when the chosen VIP is in BACKUP status,
        and started in MASTER status.
      type: str
      returned: always
    server:
      description: The IPv4 addresses of the DHCP server to relay requests to.
      type: list
      returned: always
      elements: str

"""


def run_module():
    """Runs this singleton module against /api/v2/services/dhcp_relay."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "enable": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "interface": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
            "nullable": True,
        },
        "agentoption": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "carpstatusvip": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "none",
            "nullable": True,
        },
        "server": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "str",
            "nullable": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/services/dhcp_relay", client)
    changed, resp = base_module.update_singleton(module.params)

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
