#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/services/freeradius/clients."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: services_freeradius_clients_info
description:
- Retrieve information about many Free RADIUS Clients.
short_description: Retrieve information about many Free RADIUS Clients.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  query_params:
    type: dict
    description: Optional query parameters for filtering the results.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve all Free RADIUS Clients
  pfrest.pfsense.services_freeradius_clients_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of Free RADIUS Clients returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    addr:
      description: The IP address or network of the RADIUS client(s) in CIDR notation.
        This is the IP of the NAS (switch, access point, firewall, router, etc.)
      type: str
      returned: always
    ip_version:
      description: The IP version of the this Client.
      type: str
      returned: always
    description:
      description: The description for this interface.
      type: str
      returned: always
    shortname:
      description: A short name for the client. This is generally the hostname of
        the NAS.
      type: str
      returned: always
    secret:
      description: This is the shared secret (password) which the NAS (switch, accesspoint,
        etc.) needs to communicate with the RADIUS server.
      type: str
      returned: always
    proto:
      description: The protocol the client uses.
      type: str
      returned: always
    nastype:
      description: The NAS type of the client. This is used by checkrad.pl for simultaneous
        use checks.
      type: str
      returned: always
    msgauth:
      description: RFC5080 requires Message-Authenticator in Access-Request. But older
        NAS (switches or accesspoints) do not include that.
      type: bool
      returned: always
    maxconn:
      description: Takes only effect if you use TCP as protocol. Limits the number
        of simultaneous TCP connections from a client.
      type: int
      returned: always
    naslogin:
      description: If supported by your NAS, you can use SNMP or finger for simultaneous-use
        checks instead of (s)radutmp file and accounting. Leave empty to choose (s)radutmp.
      type: str
      returned: always
    naspassword:
      description: If supported by your NAS, you can use SNMP or finger for simultaneous-use
        checks instead of (s)radutmp file and accounting. Leave empty to choose (s)radutmp.
      type: str
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/services/freeradius/clients."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "query_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/services/freeradius/clients", client)
    changed = False
    resp = base_module.lookup_objects(lookup_params=module.params["query_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
