#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/services/bind/zone."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: services_bind_zone_info
description:
- Retrieve information about a single BIND Zone.
short_description: Retrieve information about a single BIND Zone.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve BIND Zone
  pfrest.pfsense.services_bind_zone_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The BIND Zone data returned by the API.
  type: dict
  returned: always
  contains:
    disabled:
      description: Disable this BIND zone.
      type: bool
      returned: always
    name:
      description: The name of this BIND zone.
      type: str
      returned: always
    description:
      description: A description for this BIND zone.
      type: str
      returned: always
    type:
      description: The type of this BIND zone.
      type: str
      returned: always
    view:
      description: The views this BIND zone belongs to.
      type: list
      returned: always
      elements: str
    reversev4:
      description: Enable reverse DNS for this BIND zone.
      type: bool
      returned: always
    reversev6:
      description: Enable reverse IPv6 DNS for this BIND zone.
      type: bool
      returned: always
    rpz:
      description: Enable this zone as part of a response policy.
      type: bool
      returned: always
    custom:
      description: Custom BIND options for this BIND zone.
      type: str
      returned: always
    dnssec:
      description: Enable DNSSEC for this BIND zone.
      type: bool
      returned: always
    backupkeys:
      description: Enable backing up DNSSEC keys in the XML configuration for this
        BIND zone.
      type: bool
      returned: always
    slaveip:
      description: The IP address of the slave server for this BIND zone.
      type: str
      returned: always
    forwarders:
      description: The forwarders for this BIND zone.
      type: list
      returned: always
      elements: str
    ttl:
      description: The default TTL interval (in seconds) for records within this BIND
        zone without a specific TTL.
      type: int
      returned: always
    baseip:
      description: The IP address of the base domain for this zone. This sets an A
        record for the base domain.
      type: str
      returned: always
    nameserver:
      description: The SOA nameserver for this zone.
      type: str
      returned: always
    mail:
      description: The SOA email address (RNAME) for this zone. This must be in an
        FQDN format.
      type: str
      returned: always
    serial:
      description: The SOA serial number for this zone.
      type: int
      returned: always
    refresh:
      description: The SOA refresh interval for this zone. TTL-style time-unit suffixes
        are supported (e.g. 1h, 1d, 1w), otherwise time in seconds is assumed.
      type: str
      returned: always
    retry:
      description: The SOA retry interval for this zone. TTL-style time-unit suffixes
        are supported (e.g. 1h, 1d, 1w), otherwise time in seconds is assumed.
      type: str
      returned: always
    expire:
      description: The SOA expiry interval for this zone. TTL-style time-unit suffixes
        are supported (e.g. 1h, 1d, 1w), otherwise time in seconds is assumed.
      type: str
      returned: always
    minimum:
      description: The SOA minimum TTL interval (in seconds) for this zone. This is
        also referred to as the negative TTL. TTL-style time-unit suffixes are supported
        (e.g. 1h, 1d, 1w), otherwise time in seconds is assumed.
      type: str
      returned: always
    enable_updatepolicy:
      description: Enable a specific dynamic update policy for this BIND zone.
      type: bool
      returned: always
    updatepolicy:
      description: The update policy for this BIND zone.
      type: str
      returned: always
    allowupdate:
      description: The access lists that are allowed to submit dynamic updates for
        'master' zones (e.g. dynamic DNS).
      type: list
      returned: always
      elements: str
    allowtransfer:
      description: The access lists that are allowed to transfer this BIND zone.
      type: list
      returned: always
      elements: str
    allowquery:
      description: The access lists that are allowed to query this BIND zone.
      type: list
      returned: always
      elements: str
    regdhcpstatic:
      description: Register DHCP static mappings as records in this BIND zone.
      type: bool
      returned: always
    customzonerecords:
      description: Custom records for this BIND zone.
      type: str
      returned: always
    records:
      description: The records for this BIND zone.
      type: list
      returned: always
      elements: dict
      contains:
        name:
          description: The domain name for this record.
          type: str
          returned: always
        type:
          description: The type of record.
          type: str
          returned: always
        rdata:
          description: The data for this record. This can be an IP address, domain
            name, or other data depending on the record type.
          type: str
          returned: always
        priority:
          description: The priority for this record.
          type: int
          returned: always

"""


def run_module():
    """Runs this info module against /api/v2/services/bind/zone."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/services/bind/zone", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
