#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/services/freeradius/ldap."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: services_freeradius_ldap_info
description:
- Retrieve information about the FreeRADIUS LDAP.
short_description: Retrieve information about the FreeRADIUS LDAP.
requirements:
- pfSense-pkg-RESTAPI must be installed on the target system.
- pfSense-pkg-freeradius3 must be installed on the target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve FreeRADIUS LDAP
  pfrest.pfsense.services_freeradius_ldap_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The FreeRADIUS LDAP data returned by the API.
  type: dict
  returned: always
  contains:
    failover_mode:
      description: The failover/load-balancing mode used between the two LDAP servers.
      type: str
      returned: always
    server1_enable_authorize:
      description: Enables LDAP authorization support for Server 1.
      type: bool
      returned: always
    server1_enable_authenticate:
      description: Enables LDAP authentication support for Server 1.
      type: bool
      returned: always
    server1_server:
      description: The FQDN or IP address of Server 1.
      type: str
      returned: always
    server1_server_port:
      description: 'The TCP port used to connect to Server 1. Valid options are: a
        TCP/UDP port number'
      type: str
      returned: always
    server1_identity:
      description: The bind DN used to connect to Server 1.
      type: str
      returned: always
    server1_password:
      description: The password used to bind to Server 1.
      type: str
      returned: always
    server1_base_dn:
      description: The base DN used when searching Server 1.
      type: str
      returned: always
    server1_filter:
      description: The LDAP search filter used by Server 1.
      type: str
      returned: always
    server1_base_filter:
      description: The base LDAP filter used by Server 1.
      type: str
      returned: always
    server1_ldap_connections_number:
      description: The maximum number of LDAP connections opened to Server 1.
      type: int
      returned: always
    server1_timeout:
      description: The bind/operation timeout (in seconds) used with Server 1.
      type: int
      returned: always
    server1_time_limit:
      description: The LDAP search time limit (in seconds) used with Server 1.
      type: int
      returned: always
    server1_net_timeout:
      description: The TCP network timeout (in seconds) used with Server 1.
      type: int
      returned: always
    server1_msad_compatibility_enable:
      description: Enables Microsoft Active Directory compatibility mode for Server
        1.
      type: str
      returned: always
    server1_misc_enable:
      description: Enables the miscellaneous (Default Profile / Profile Attribute
        / Access Attribute) block for Server 1.
      type: bool
      returned: always
    server1_default_profile:
      description: The default profile DN used by Server 1.
      type: str
      returned: always
    server1_profile_attribute:
      description: The LDAP profile attribute used by Server 1.
      type: str
      returned: always
    server1_access_attribute:
      description: The LDAP access attribute used by Server 1.
      type: str
      returned: always
    server1_group_enable:
      description: Enables LDAP group membership lookups for Server 1.
      type: bool
      returned: always
    server1_groupname_attribute:
      description: The LDAP group name attribute used by Server 1.
      type: str
      returned: always
    server1_group_membership_filter:
      description: The LDAP group membership filter used by Server 1.
      type: str
      returned: always
    server1_group_membership_attribute:
      description: The LDAP group membership attribute used by Server 1.
      type: str
      returned: always
    server1_compare_check_items:
      description: Whether Server 1 should compare check items.
      type: str
      returned: always
    server1_do_xlat:
      description: Whether Server 1 should perform attribute translation (xlat).
      type: str
      returned: always
    server1_access_attr_used_for_allow:
      description: Whether the access attribute is used to allow (Server 1).
      type: str
      returned: always
    server1_keepalive_idle:
      description: The TCP KeepAlive idle interval (in seconds) used with Server 1.
      type: int
      returned: always
    server1_keepalive_probes:
      description: The number of TCP KeepAlive probes used with Server 1.
      type: int
      returned: always
    server1_keepalive_interval:
      description: The TCP KeepAlive interval (in seconds) used with Server 1.
      type: int
      returned: always
    server1_enable_tls_support:
      description: Enables TLS support when connecting to Server 1.
      type: bool
      returned: always
    server1_enable_starttls:
      description: Use STARTTLS when establishing a TLS-protected connection to Server
        1.
      type: bool
      returned: always
    server1_ssl_ca_cert:
      description: The Certificate Authority (refid) used to verify the Server 1 server
        certificate when TLS support is enabled.
      type: str
      returned: always
    server1_ssl_server_cert:
      description: The client Certificate (refid) presented when establishing a TLS
        connection to Server 1.
      type: str
      returned: always
    server1_require_cert:
      description: The certificate verification mode used when connecting to Server
        1 with TLS support.
      type: str
      returned: always
    server2_enable_authorize:
      description: Enables LDAP authorization support for Server 2.
      type: bool
      returned: always
    server2_enable_authenticate:
      description: Enables LDAP authentication support for Server 2.
      type: bool
      returned: always
    server2_server:
      description: The FQDN or IP address of Server 2.
      type: str
      returned: always
    server2_server_port:
      description: 'The TCP port used to connect to Server 2. Valid options are: a
        TCP/UDP port number'
      type: str
      returned: always
    server2_identity:
      description: The bind DN used to connect to Server 2.
      type: str
      returned: always
    server2_password:
      description: The password used to bind to Server 2.
      type: str
      returned: always
    server2_base_dn:
      description: The base DN used when searching Server 2.
      type: str
      returned: always
    server2_filter:
      description: The LDAP search filter used by Server 2.
      type: str
      returned: always
    server2_base_filter:
      description: The base LDAP filter used by Server 2.
      type: str
      returned: always
    server2_ldap_connections_number:
      description: The maximum number of LDAP connections opened to Server 2.
      type: int
      returned: always
    server2_timeout:
      description: The bind/operation timeout (in seconds) used with Server 2.
      type: int
      returned: always
    server2_time_limit:
      description: The LDAP search time limit (in seconds) used with Server 2.
      type: int
      returned: always
    server2_net_timeout:
      description: The TCP network timeout (in seconds) used with Server 2.
      type: int
      returned: always
    server2_msad_compatibility_enable:
      description: Enables Microsoft Active Directory compatibility mode for Server
        2.
      type: str
      returned: always
    server2_misc_enable:
      description: Enables the miscellaneous (Default Profile / Profile Attribute
        / Access Attribute) block for Server 2.
      type: bool
      returned: always
    server2_default_profile:
      description: The default profile DN used by Server 2.
      type: str
      returned: always
    server2_profile_attribute:
      description: The LDAP profile attribute used by Server 2.
      type: str
      returned: always
    server2_access_attribute:
      description: The LDAP access attribute used by Server 2.
      type: str
      returned: always
    server2_group_enable:
      description: Enables LDAP group membership lookups for Server 2.
      type: bool
      returned: always
    server2_groupname_attribute:
      description: The LDAP group name attribute used by Server 2.
      type: str
      returned: always
    server2_group_membership_filter:
      description: The LDAP group membership filter used by Server 2.
      type: str
      returned: always
    server2_group_membership_attribute:
      description: The LDAP group membership attribute used by Server 2.
      type: str
      returned: always
    server2_compare_check_items:
      description: Whether Server 2 should compare check items.
      type: str
      returned: always
    server2_do_xlat:
      description: Whether Server 2 should perform attribute translation (xlat).
      type: str
      returned: always
    server2_access_attr_used_for_allow:
      description: Whether the access attribute is used to allow (Server 2).
      type: str
      returned: always
    server2_keepalive_idle:
      description: The TCP KeepAlive idle interval (in seconds) used with Server 2.
      type: int
      returned: always
    server2_keepalive_probes:
      description: The number of TCP KeepAlive probes used with Server 2.
      type: int
      returned: always
    server2_keepalive_interval:
      description: The TCP KeepAlive interval (in seconds) used with Server 2.
      type: int
      returned: always
    server2_enable_tls_support:
      description: Enables TLS support when connecting to Server 2.
      type: bool
      returned: always
    server2_enable_starttls:
      description: Use STARTTLS when establishing a TLS-protected connection to Server
        2.
      type: bool
      returned: always
    server2_ssl_ca_cert:
      description: The Certificate Authority (refid) used to verify the Server 2 server
        certificate when TLS support is enabled.
      type: str
      returned: always
    server2_ssl_server_cert:
      description: The client Certificate (refid) presented when establishing a TLS
        connection to Server 2.
      type: str
      returned: always
    server2_require_cert:
      description: The certificate verification mode used when connecting to Server
        2 with TLS support.
      type: str
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/services/freeradius/ldap."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/services/freeradius/ldap", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
