#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/services/cron/job."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: services_cron_job
description:
- Manage individual Cron Jobs.
short_description: Manage individual Cron Jobs.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: true
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource.
  minute:
    required: true
    type: str
    default: null
    choices: []
    description: The minute(s) at which the command will be executed or a special
      @ event string. (0-59, ranges, divided, @ event or delay, *=all). When using
      a special @ event, such as @reboot, the other time fields must be empty.
  hour:
    required: false
    type: str
    default: null
    choices: []
    description: The hour(s) at which the command will be executed. (0-23, ranges,
      or divided, *=all)
  mday:
    required: false
    type: str
    default: null
    choices: []
    description: The day(s) of the month on which the command will be executed. (1-31,
      ranges, or divided, *=all).
  month:
    required: false
    type: str
    default: null
    choices: []
    description: The month(s) of the year in which the command will be executed. (1-31,
      ranges, or divided, *=all).
  wday:
    required: false
    type: str
    default: null
    choices: []
    description: The day(s) of the week on which the command will be executed. (0-7,
      7=Sun or use names, ranges, or divided, *=all).
  who:
    required: true
    type: str
    default: null
    choices: []
    description: The OS user to use when cron runs the command.
  command:
    required: true
    type: str
    default: null
    choices: []
    description: The command to run. Use full file paths for this command and include
      an command parameters.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Create Cron Job
  pfrest.pfsense.services_cron_job:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: present
    minute: string
    hour: string
    mday: string
    month: string
    wday: string
    who: string
    command: string
- name: Delete Cron Job
  pfrest.pfsense.services_cron_job:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: absent
    minute: string
    hour: string
    mday: string
    month: string
    wday: string
    who: string
    command: string

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Cron Job data returned by the API.
  type: dict
  returned: always
  contains:
    minute:
      description: The minute(s) at which the command will be executed or a special
        @ event string. (0-59, ranges, divided, @ event or delay, *=all). When using
        a special @ event, such as @reboot, the other time fields must be empty.
      type: str
      returned: always
    hour:
      description: The hour(s) at which the command will be executed. (0-23, ranges,
        or divided, *=all)
      type: str
      returned: always
    mday:
      description: The day(s) of the month on which the command will be executed.
        (1-31, ranges, or divided, *=all).
      type: str
      returned: always
    month:
      description: The month(s) of the year in which the command will be executed.
        (1-31, ranges, or divided, *=all).
      type: str
      returned: always
    wday:
      description: The day(s) of the week on which the command will be executed. (0-7,
        7=Sun or use names, ranges, or divided, *=all).
      type: str
      returned: always
    who:
      description: The OS user to use when cron runs the command.
      type: str
      returned: always
    command:
      description: The command to run. Use full file paths for this command and include
        an command parameters.
      type: str
      returned: always

"""


def run_module():
    """Runs this resource module against /api/v2/services/cron/job."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "state": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "present",
            "choices": ["present", "absent"],
        },
        "lookup_fields": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "str",
        },
        "minute": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "hour": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "mday": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "month": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "wday": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "who": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "command": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/services/cron/job", client)
    changed, resp = base_module.set_object_state(
        state=module.params["state"],
        data=module.params,
        lookup_fields=module.params["lookup_fields"],
        parent_lookup_fields=module.params.get("parent_lookup_fields", []),
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
