#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: services_dns_forwarder_host_overrides
description:
- Manage all DNS Forwarder Host Overrides.
short_description: Manage all DNS Forwarder Host Overrides.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  objects:
    type: list
    elements: dict
    required: true
    suboptions:
      host:
        required: true
        type: str
        default: null
        choices: []
        description: The hostname of this override.
      domain:
        required: true
        type: str
        default: null
        choices: []
        description: The domain of this override.
      ip:
        required: true
        type: str
        default: null
        choices: []
        description: The IP address of this override.
      descr:
        required: false
        type: str
        default: ''
        choices: []
        description: The description for this override.
      aliases:
        required: false
        type: list
        default: []
        choices: []
        description: The aliases for this override.
    description: The list of items to manage in the collection. Each item should be
      a dictionary representing the desired state of a single resource within the
      collection.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Manage all DNS Forwarder Host Overrides
  pfrest.pfsense.services_dns_forwarder_host_overrides:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    objects:
    - host: example
      domain: example
      ip: example
      descr: example
      aliases: []

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of DNS Forwarder Host Overrides returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    host:
      description: The hostname of this override.
      type: str
      returned: always
    domain:
      description: The domain of this override.
      type: str
      returned: always
    ip:
      description: The IP address of this override.
      type: str
      returned: always
    descr:
      description: The description for this override.
      type: str
      returned: always
    aliases:
      description: The aliases for this override.
      type: list
      returned: always
      elements: dict
      contains:
        host:
          description: The hostname of this override alias.
          type: str
          returned: always
        domain:
          description: The domain of this override alias.
          type: str
          returned: always
        description:
          description: The description of this override alias.
          type: str
          returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "objects": {
            "type": list,
            "required": True,
            "default": None,
            "choices": [],
            "elements": "dict",
            "suboptions": {'host': {'required': True, 'type': 'str', 'default': None, 'choices': [], 'description': 'The hostname of this override.'}, 'domain': {'required': True, 'type': 'str', 'default': None, 'choices': [], 'description': 'The domain of this override.'}, 'ip': {'required': True, 'type': 'str', 'default': None, 'choices': [], 'description': 'The IP address of this override.'}, 'descr': {'required': False, 'type': 'str', 'default': '', 'choices': [], 'description': 'The description for this override.'}, 'aliases': {'required': False, 'type': 'list', 'default': [], 'choices': [], 'description': 'The aliases for this override.'}},
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule(client)
    changed = True # TODO: determine if changes are needed by comparing existing objects to the provided list
    resp = base_module.replace_objects(
        data=module.params['objects'],
    )

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if resp['status'] != 200:
        module.fail_json(msg=resp['message'], **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()