#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: services_haproxy_frontend
description:
- Manage individual HA Proxy Frontends.
short_description: Manage individual HA Proxy Frontends.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  name:
    required: true
    type: str
    default: null
    choices: []
    description: The unique name for this HAProxy frontend.
  descr:
    required: false
    type: str
    default: ''
    choices: []
    description: The description for this HAProxy frontend.
  status:
    required: false
    type: str
    default: active
    choices:
    - active
    - disabled
    description: The activation status for this HAProxy frontend.
  a_extaddr:
    required: false
    type: list
    default: []
    choices: []
    description: The external addresses assigned to this frontend.
  max_connections:
    required: false
    type: int
    default: null
    choices: []
    description: The maximum number of connections allowed by this frontend.
  type:
    required: true
    type: str
    default: null
    choices:
    - http
    - https
    - tcp
    description: The processing type for this frontend.
  ha_acls:
    required: false
    type: list
    default: []
    choices: []
    description: The ACLs to apply to this frontend.
  a_actionitems:
    required: false
    type: list
    default: []
    choices: []
    description: The actions to take when an ACL match is found.
  backend_serverpool:
    required: false
    type: str
    default: null
    choices: []
    description: The default backend to use for this frontend.
  socket_stats:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables collecting and providing separate statistics
      for each socket.
  dontlognull:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables logging connections with no data transferred.
  dontlog_normal:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables only logging anomalous (not normal) connection.
  log_separate_errors:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables changing the log level from info to err on potentially
      interesting info.
  log_detailed:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables more detailed logging.
  a_errorfiles:
    required: false
    type: list
    default: []
    choices: []
    description: The custom error files to use for this frontend.
  client_timeout:
    required: false
    type: int
    default: 30000
    choices: []
    description: The amount of time (in milliseconds) to wait for data from the client.
  forwardfor:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the HTTP X-Forwarded-For header which contains
      the client's IP address.
  httpclose:
    required: false
    type: str
    default: http-keep-alive
    choices:
    - http-keep-alive
    - http-tunnel
    - httpclose
    - http-server-close
    - forceclose
    description: The `httpclose` option this frontend will operate.
  advanced_bind:
    required: false
    type: str
    default: null
    choices: []
    description: Custom value to pass behind each bind option.
  advanced:
    required: false
    type: str
    default: null
    choices: []
    description: Custom configuration to pass to this frontend.
  ssloffloadcert:
    required: false
    type: str
    default: null
    choices: []
    description: The default SSL/TLS certificate refid to use for this frontend.
  ha_certificates:
    required: false
    type: list
    default: []
    choices: []
    description: The additional SSL/TLS certificates to use on this frontend.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "name": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "descr": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "status": {
            "type": str,
            "required": False,
            "default": 'active',
            "choices": ['active', 'disabled'],
        },
        "a_extaddr": {
            "type": list,
            "required": False,
            "default": [],
            "choices": [],
        },
        "max_connections": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "type": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['http', 'https', 'tcp'],
        },
        "ha_acls": {
            "type": list,
            "required": False,
            "default": [],
            "choices": [],
        },
        "a_actionitems": {
            "type": list,
            "required": False,
            "default": [],
            "choices": [],
        },
        "backend_serverpool": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "socket_stats": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "dontlognull": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "dontlog_normal": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "log_separate_errors": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "log_detailed": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "a_errorfiles": {
            "type": list,
            "required": False,
            "default": [],
            "choices": [],
        },
        "client_timeout": {
            "type": int,
            "required": False,
            "default": 30000,
            "choices": [],
        },
        "forwardfor": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "httpclose": {
            "type": str,
            "required": False,
            "default": 'http-keep-alive',
            "choices": ['http-keep-alive', 'http-tunnel', 'httpclose', 'http-server-close', 'forceclose'],
        },
        "advanced_bind": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "advanced": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "ssloffloadcert": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "ha_certificates": {
            "type": list,
            "required": False,
            "default": [],
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()