#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/status/system."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: status_system_info
description:
- Retrieve information about the System Status.
short_description: Retrieve information about the System Status.
requirements:
- L(pfSense-pkg-RESTAPI,https://pfrest.org) must be installed on the target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve System Status
  pfrest.pfsense.status_system_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The System Status data returned by the API.
  type: dict
  returned: always
  contains:
    platform:
      description: The verbose name of this system's platform.
      type: str
      returned: always
    serial:
      description: The system's unique serial number/ID.
      type: str
      returned: always
    netgate_id:
      description: The unique ID issued for this pfSense instance by Netgate.
      type: str
      returned: always
    uptime:
      description: The amount of time this system has been up since the last reboot.
      type: str
      returned: always
    bios_vendor:
      description: The name of the BIOS vendor.
      type: str
      returned: always
    bios_version:
      description: The BIOS version installed on this system.
      type: str
      returned: always
    bios_date:
      description: The build date of the BIOS version.
      type: str
      returned: always
    kernel_pti:
      description: Indicates whether kernel PTI is enabled or not.
      type: bool
      returned: always
    mds_mitigation:
      description: Indicates whether MDS mitigation is enabled or not.
      type: str
      returned: always
    temp_c:
      description: The current system temperature in celsius.
      type: str
      returned: always
    temp_f:
      description: The current system temperature in fahrenheit.
      type: str
      returned: always
    cpu_model:
      description: The model of CPU installed in this system and other CPU info.
      type: str
      returned: always
    cpu_load_avg:
      description: The CPU load averages. The first value represents the load average
        for the last minute, the second value represents the load average for the
        last 5 minutes, and the third value represents the load average for the last
        15 minutes.
      type: list
      returned: always
      elements: str
    cpu_count:
      description: The total number of CPUs cores available on this system.
      type: int
      returned: always
    cpu_usage:
      description: 'The current CPU usage as a whole percentage. Note: This is an
        approximate usage based on the last minute load average and total number of
        CPU cores. This may not represent exact CPU usage.'
      type: str
      returned: always
    mbuf_usage:
      description: The current MBUF usage as a whole percentage.
      type: str
      returned: always
    mem_usage:
      description: The current memory usage as a whole percentage.
      type: str
      returned: always
    swap_usage:
      description: The current swap usage as a whole percentage.
      type: str
      returned: always
    disk_usage:
      description: The current disk usage as a whole percentage.
      type: str
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/status/system."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/status/system", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
