#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: status_openvpn_server_connections_info
description:
- Retrieve information about many OpenVPN Server Connection Statuses.
short_description: Retrieve information about many OpenVPN Server Connection Statuses.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  query_params:
    type: dict
    description: Optional query parameters for filtering the results.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Retrieve all OpenVPN Server Connection Statuses
  pfrest.pfsense.status_openvpn_server_connections_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of OpenVPN Server Connection Statuses returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    common_name:
      description: The common name of the OpenVPN server connection.
      type: str
      returned: always
    remote_host:
      description: The remote host of the OpenVPN server connection.
      type: str
      returned: always
    virtual_addr:
      description: The virtual address of the OpenVPN server connection.
      type: str
      returned: always
    virtual_addr6:
      description: The virtual IPv6 address of the OpenVPN server connection.
      type: str
      returned: always
    bytes_recv:
      description: The number of bytes received by the OpenVPN server connection.
      type: int
      returned: always
    bytes_sent:
      description: The number of bytes sent by the OpenVPN server connection.
      type: int
      returned: always
    connect_time:
      description: The connection time of the OpenVPN server connection.
      type: str
      returned: always
    connect_time_unix:
      description: The connection time of the OpenVPN server connection in Unix time.
      type: int
      returned: always
    user_name:
      description: The user name of the OpenVPN server connection.
      type: str
      returned: always
    client_id:
      description: The client ID of the OpenVPN server connection.
      type: int
      returned: always
    peer_id:
      description: The peer ID of the OpenVPN server connection.
      type: int
      returned: always
    cipher:
      description: The cipher of the OpenVPN server connection.
      type: str
      returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "query_params": {
            "type": dict,
            "required": False,
            "default": None,
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule(client)
    changed = False
    resp = base_module.lookup_objects(lookup_params=module.params['query_params'])

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if resp['status'] != 200:
        module.fail_json(msg=resp['message'], **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()