#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: system_restapi_settings
description:
- Manage REST API Settings.
short_description: Manage REST API Settings.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  enabled:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables the API. If set to `false`, the API will no longer
      respond to API requests and can only be re-enabled via webConfigurator.
  read_only:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables read-only API access. If enabled, the API will
      only respond to GET requests and can only be disabled via webConfigurator.
  keep_backup:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables keeping a persistent backup of the API configuration
      that can be used to restore the API configuration after package and systems
      updates.
  login_protection:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables Login Protection for API authentication. When
      enabled, Login Protection will monitor API attempts and temporarily block clients
      who fail API authentication too many times within a period of time. When disabled,
      Login Protection will not monitor API authentication but will continue to monitor
      webConfigurator and SSH logins (if configured). Login Protection can be configured
      globally in System > Advanced.
  log_successful_auth:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables logging of API authentication attempts that are
      successful. By default, only failed API authentication attempts are logged to
      prevent flooding the authentication logs. This field is only applicable when
      the API `login_protection` setting is enabled.
  log_level:
    required: false
    type: str
    default: LOG_WARNING
    choices:
    - LOG_DEBUG
    - LOG_INFO
    - LOG_NOTICE
    - LOG_WARNING
    - LOG_ERR
    - LOG_CRIT
    - LOG_ALERT
    - LOG_EMERG
    description: Sets the log level for API logging. The log level determines the
      minimum severity of messages that should be logged.
  allow_pre_releases:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables displaying pre-releases in available API updates.
      Pre-releases contain fixes and features that are currently under development
      and may not be fully stable. Use of pre-release versions is at your own risk.
  hateoas:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables HATEOAS. Enabling HATEOAS will allow the API
      to include links to related resources in API responses. This is primarily useful
      for frontend web applications and self-navigating client scripts that integrate
      with HAL standards. Enabling HATEOAS may increase API response times, especially
      on systems with large configurations.
  expose_sensitive_fields:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables exposing sensitive fields in API responses. When
      enabled, sensitive fields such as passwords, private keys, and other sensitive
      data will be included in API responses.
  override_sensitive_fields:
    required: false
    type: str
    default: []
    choices: []
    description: Specifies a list of fields (formatted as ModelName:FieldName) that
      should have their sensitive attribute overridden. Fields selected here will
      not be considered sensitive and will be included in API responses regardless
      of the `expose_sensitive_fields` setting.
  allowed_interfaces:
    required: false
    type: str
    default: []
    choices: []
    description: Sets the interfaces allowed to accept incoming API calls.
  represent_interfaces_as:
    required: false
    type: str
    default: descr
    choices:
    - descr
    - id
    - if
    description: Specifies how the API should represent interface names. Use `descr`
      to represent interface objects by their description name, use `id` to represent
      interface objects by their internal pfSense ID (e.g. wan, lan, opt1), or use
      `if` to represent interface objects by their real interface name (e.g. em0,
      igb1, bxe3).
  auth_methods:
    required: false
    type: str
    default:
    - BasicAuth
    choices: []
    description: Sets the API authentication methods allowed to authenticate API calls.
  jwt_exp:
    required: false
    type: int
    default: 3600
    choices: []
    description: Sets the amount of time (in seconds) JWTs are valid for.
  ha_sync:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables syncing API settings to HA peers. When enabled,
      API settings from this host will automatically be synced to any hosts defined
      in `ha_sync_hosts`.
  ha_sync_validate_certs:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables certificate validation when syncing API configurations
      to HA sync peers. If enabled, all hosts defined in `ha_sync_hosts` must have
      their webConfigurator configured with a certificate trusted by this system.
      It is strongly recommended this be enabled at all times to help mitigate Man-in-the-Middle
      attacks.
  ha_sync_hosts:
    required: false
    type: str
    default: []
    choices: []
    description: Set a list of IP addresses or hostnames to sync API settings to.
  ha_sync_username:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the username to use when authenticating for HA sync processes.
      This user must be the present on all hosts defined in `ha_sync_hosts`.
  ha_sync_password:
    required: false
    type: str
    default: ''
    choices: []
    description: Sets the password to use when authenticating for HA sync processes.
      This must be the password for the user defined in `ha_sync_username` and must
      be the same on all hosts defined in `ha_sync_hosts`.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "enabled": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "read_only": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "keep_backup": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "login_protection": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "log_successful_auth": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "log_level": {
            "type": str,
            "required": False,
            "default": 'LOG_WARNING',
            "choices": ['LOG_DEBUG', 'LOG_INFO', 'LOG_NOTICE', 'LOG_WARNING', 'LOG_ERR', 'LOG_CRIT', 'LOG_ALERT', 'LOG_EMERG'],
        },
        "allow_pre_releases": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "hateoas": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "expose_sensitive_fields": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "override_sensitive_fields": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "allowed_interfaces": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "represent_interfaces_as": {
            "type": str,
            "required": False,
            "default": 'descr',
            "choices": ['descr', 'id', 'if'],
        },
        "auth_methods": {
            "type": str,
            "required": False,
            "default": ['BasicAuth'],
            "choices": [],
        },
        "jwt_exp": {
            "type": int,
            "required": False,
            "default": 3600,
            "choices": [],
        },
        "ha_sync": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ha_sync_validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "ha_sync_hosts": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "ha_sync_username": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "ha_sync_password": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()