#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: system_notifications_email_settings
description:
- Manage Email Notification Settings.
short_description: Manage Email Notification Settings.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  disable:
    required: false
    type: bool
    default: false
    choices: []
    description: Disables SMTP notifications.
  ipaddress:
    required: false
    type: str
    default: ''
    choices: []
    description: The IP address or hostname of the SMTP server.
  port:
    required: false
    type: str
    default: '25'
    choices: []
    description: 'The port number of the SMTP server. Valid options are: a TCP/UDP
      port number'
  timeout:
    required: false
    type: int
    default: 20
    choices: []
    description: The timeout (in seconds) for the SMTP connection.
  ssl:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables SSL/TLS for the SMTP connection.
  sslvalidate:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables SSL/TLS certificate validation for the SMTP connection.
  fromaddress:
    required: false
    type: str
    default: ''
    choices: []
    description: The email address to use as the "From" address in notifications.
  notifyemailaddress:
    required: false
    type: str
    default: ''
    choices: []
    description: The email address to send notifications to.
  authentication_mechanism:
    required: false
    type: str
    default: PLAIN
    choices:
    - PLAIN
    - LOGIN
    description: The authentication mechanism to use for the SMTP connection.
  username:
    required: true
    type: str
    default: null
    choices: []
    description: The username to use for SMTP authentication.
  password:
    required: true
    type: str
    default: null
    choices: []
    description: The password to use for SMTP authentication.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "disable": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ipaddress": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "port": {
            "type": str,
            "required": False,
            "default": '25',
            "choices": [],
        },
        "timeout": {
            "type": int,
            "required": False,
            "default": 20,
            "choices": [],
        },
        "ssl": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "sslvalidate": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "fromaddress": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "notifyemailaddress": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "authentication_mechanism": {
            "type": str,
            "required": False,
            "default": 'PLAIN',
            "choices": ['PLAIN', 'LOGIN'],
        },
        "username": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "password": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()