#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/system/restapi/access_list."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: system_restapi_access_list
description:
- Manage all REST API Access List Entries.
short_description: Manage all REST API Access List Entries.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  objects:
    type: list
    elements: dict
    required: true
    suboptions:
      type:
        required: false
        type: str
        default: allow
        choices:
        - allow
        - deny
        description: The type of access this entry provides. "allow" entries permit
          access to the REST API from the specified networks. "deny" entries block
          access to the REST API from the specified networks.
      weight:
        required: false
        type: int
        default: 1
        choices: []
        description: The weight of this entry. Entries with lower weights are evaluated
          first. If multiple entries match a request, the entry with the lowest weight
          will be applied.
      network:
        required: true
        type: str
        default: null
        choices: []
        description: The network (in CIDR notation) that this entry applies to. Clients
          interacting with the REST API from this network will be affected by this
          entry.
      users:
        required: false
        type: list
        default: []
        choices: []
        description: The users that this entry applies to. Only users in this list
          will be affected by this entry. Leave empty if this entry should apply to
          all users.
        elements: str
      sched:
        required: false
        type: str
        default: ''
        choices: []
        description: The firewall schedule that this entry will use. This entry will
          only be active during the times specified in the schedule. Leave empty to
          apply this entry at all times.
      descr:
        required: false
        type: str
        default: ''
        choices: []
        description: A description of this access list entry. This field is optional.
    description: The list of items to manage in the collection. Each item should be
      a dictionary representing the desired state of a single resource within the
      collection.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Manage all REST API Access List Entries
  pfrest.pfsense.system_restapi_access_list:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    objects:
    - network: string
      type: allow
      weight: 1

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of REST API Access List Entries returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    type:
      description: The type of access this entry provides. "allow" entries permit
        access to the REST API from the specified networks. "deny" entries block access
        to the REST API from the specified networks.
      type: str
      returned: always
    weight:
      description: The weight of this entry. Entries with lower weights are evaluated
        first. If multiple entries match a request, the entry with the lowest weight
        will be applied.
      type: int
      returned: always
    network:
      description: The network (in CIDR notation) that this entry applies to. Clients
        interacting with the REST API from this network will be affected by this entry.
      type: str
      returned: always
    users:
      description: The users that this entry applies to. Only users in this list will
        be affected by this entry. Leave empty if this entry should apply to all users.
      type: list
      returned: always
      elements: str
    sched:
      description: The firewall schedule that this entry will use. This entry will
        only be active during the times specified in the schedule. Leave empty to
        apply this entry at all times.
      type: str
      returned: always
    descr:
      description: A description of this access list entry. This field is optional.
      type: str
      returned: always

"""


def run_module():
    """Runs this collection module against /api/v2/system/restapi/access_list."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "objects": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "dict",
            "options": {
                "type": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "allow",
                    "choices": ["allow", "deny"],
                },
                "weight": {
                    "type": "int",
                    "required": False,
                    "no_log": False,
                    "default": 1,
                },
                "network": {
                    "type": "str",
                    "required": True,
                    "no_log": False,
                    "default": None,
                },
                "users": {
                    "type": "list",
                    "required": False,
                    "no_log": False,
                    "default": [],
                    "elements": "str",
                },
                "sched": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "",
                },
                "descr": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "",
                },
            },
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/system/restapi/access_list", client)
    changed, resp = base_module.replace_objects(
        data=module.params["objects"],
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
