#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/system/certificate/pkcs12/export."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: system_certificate_pkcs12_export
description:
- Perform the Certificate PKCS#12 Export action.
short_description: Perform the Certificate PKCS#12 Export action.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  certref:
    required: true
    type: str
    default: null
    choices: []
    description: The Certificate to export as a PKCS12 file.
  encryption:
    required: false
    type: str
    default: high
    choices:
    - high
    - low
    - legacy
    description: The level of encryption to use when exporting the PKCS#12 archive.
  passphrase:
    required: false
    type: str
    default: ''
    choices: []
    description: The passphrase to use when exporting the PKCS#12 archive. Leave empty
      for no passphrase.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Perform Certificate PKCS#12 Export action
  pfrest.pfsense.system_certificate_pkcs12_export:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    certref: string

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Certificate PKCS#12 Export data returned by the API.
  type: dict
  returned: always
  contains:
    certref:
      description: The Certificate to export as a PKCS12 file.
      type: str
      returned: always
    encryption:
      description: The level of encryption to use when exporting the PKCS#12 archive.
      type: str
      returned: always
    passphrase:
      description: The passphrase to use when exporting the PKCS#12 archive. Leave
        empty for no passphrase.
      type: str
      returned: always
    filename:
      description: The filename used when exporting the PKCS#12 archive. This value
        cannot be changed and will always be certificate refid with the .p12 extension.
      type: str
      returned: always
    binary_data:
      description: The PKCS#12 archive binary data. This value cannot be changed.
      type: str
      returned: always

"""


def run_module():
    """Runs this action module against /api/v2/system/certificate/pkcs12/export."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "certref": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "encryption": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "high",
            "choices": ["high", "low", "legacy"],
        },
        "passphrase": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/system/certificate/pkcs12/export", client)
    changed, resp = base_module.execute_action(data=module.params)

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
