#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: user_info
description:
- Retrieve information about a single User.
short_description: Retrieve information about a single User.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''

EXAMPLES = '''
- name: Retrieve User
  pfrest.pfsense.user_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

'''

RETURNS = '''
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The User data returned by the API.
  type: dict
  returned: always
  contains:
    name:
      description: The username of this local user.
      type: str
      returned: always
    password:
      description: The password of this local user.
      type: str
      returned: always
    uid:
      description: The UID of this local user. This value is automatically assigned
        and cannot be changed.
      type: int
      returned: always
    scope:
      description: The scope of this local user. This value is automatically assigned
        and cannot be changed.
      type: str
      returned: always
    priv:
      description: The privileges assigned to this local user.
      type: str
      returned: always
    disabled:
      description: Disable this local user.
      type: bool
      returned: always
    descr:
      description: The full descriptive name for this local user.
      type: str
      returned: always
    expires:
      description: The expiration date for this user in mm/dd/YYYY format. Use empty
        string for no expiration
      type: str
      returned: always
    cert:
      description: The user certificates to assign this user. Items must be existing
        certificate `refid`s.
      type: str
      returned: always
    authorizedkeys:
      description: The SSH authorized keys to assign this user.
      type: str
      returned: always
    ipsecpsk:
      description: The IPsec pre-shared key to assign this user.
      type: str
      returned: always

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "lookup_params": {
            "type": dict,
            "required": False,
            "default": None,
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule(client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params['lookup_params'])

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if resp['status'] != 200:
        module.fail_json(msg=resp['message'], **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()