#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = '''
module: user_auth_server
description:
- Manage individual authentication servers.
short_description: Manage individual authentication servers.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: false
    default: null
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource. If not specified,
      the module will attempt to use the 'id' field if it exists, or all fields marked
      as 'unique' in the schema.
  type:
    required: true
    type: str
    default: null
    choices:
    - ldap
    - radius
    description: The type of this authentication server.
  name:
    required: true
    type: str
    default: null
    choices: []
    description: The descriptive name for this authentication server.
  host:
    required: true
    type: str
    default: null
    choices: []
    description: The remote IP address or hostname of the authentication server.
  ldap_port:
    required: true
    type: str
    default: null
    choices: []
    description: 'The LDAP port to connect to on this LDAP authentication server.
      Valid options are: a TCP/UDP port number'
  ldap_urltype:
    required: true
    type: str
    default: null
    choices:
    - Standard TCP
    - STARTTLS Encrypt
    - SSL/TLS Encrypted
    description: The encryption mode to use when connecting to this authentication
      server. Use `Standard TCP` for unencrypted LDAP connections, use `STARTTLS Encrypt`
      to start an encrypted connection via STARTTLS if it's available, or `SSL/TLS
      Encrypted` to only use LDAPS encrypted connections.
  ldap_protver:
    required: false
    type: int
    default: 3
    choices:
    - 2
    - 3
    description: The LDAP protocol version to use for connections to this LDAP authentication
      server.
  ldap_timeout:
    required: false
    type: int
    default: 25
    choices: []
    description: The timeout (in seconds) for connections to the LDAP authentication
      server.
  ldap_caref:
    required: false
    type: str
    default: global
    choices: []
    description: The certificate authority used to validate the LDAP server certificate.
  ldap_scope:
    required: true
    type: str
    default: null
    choices:
    - one
    - subtree
    description: The LDAP search scope. Use `one` to limit the scope to a single level,
      or `subtree` to allow the entire subtree to be searched.
  ldap_basedn:
    required: false
    type: str
    default: ''
    choices: []
    description: The root for LDAP searches on this authentication server.
  ldap_authcn:
    required: false
    type: str
    default: ''
    choices: []
    description: The LDAP authentication container.
  ldap_extended_enabled:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable LDAP extended queries.
  ldap_extended_query:
    required: false
    type: str
    default: ''
    choices: []
    description: The extended LDAP query to make during LDAP searches.
  ldap_binddn:
    required: false
    type: str
    default: null
    choices: []
    description: The DN to use when binding to this authentication server. Set to
      `null` to bind anonymously.
  ldap_bindpw:
    required: true
    type: str
    default: null
    choices: []
    description: The password to use when binding to this authentication server.
  ldap_attr_user:
    required: false
    type: str
    default: cn
    choices: []
    description: The LDAP user attribute.
  ldap_attr_group:
    required: false
    type: str
    default: cn
    choices: []
    description: The LDAP group attribute.
  ldap_attr_member:
    required: false
    type: str
    default: member
    choices: []
    description: The LDAP member attribute.
  ldap_rfc2307:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disable RFC2307 LDAP options.
  ldap_rfc2307_userdn:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disable the use of DNs for username searches.
  ldap_attr_groupobj:
    required: false
    type: str
    default: posixGroup
    choices: []
    description: The group object class for groups in RFC2307 mode.
  ldap_pam_groupdn:
    required: false
    type: str
    default: ''
    choices: []
    description: The group DN to use for shell authentication. Users must be a member
      of this group and have valid posixAccount attributes to sign in.
  ldap_utf8:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables UTF-8 encoding LDAP parameters before sending
      them to this authentication server
  ldap_nostrip_at:
    required: false
    type: bool
    default: false
    choices: []
    description: Do not strip away parts of the username after the @ symbol.
  ldap_allow_unauthenticated:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables unauthenticated binding. Unauthenticated binds
      are bind with an existing login but with an empty password. Some LDAP servers
      (Microsoft AD) allow this type of bind without any possibility to disable it.
  radius_secret:
    required: true
    type: str
    default: null
    choices: []
    description: The shared secret to use when authenticating to this RADIUS server.
  radius_auth_port:
    required: false
    type: str
    default: '1812'
    choices: []
    description: 'The port used by RADIUS for authentication. Set to `null` to disable
      use of authentication services. Valid options are: a TCP/UDP port number'
  radius_acct_port:
    required: false
    type: str
    default: '1813'
    choices: []
    description: 'The port used by RADIUS for accounting. Set to `null` to disable
      use of accounting services. Valid options are: a TCP/UDP port number'
  radius_protocol:
    required: false
    type: str
    default: MSCHAPv2
    choices:
    - MSCHAPv2
    - MSCHAPv1
    - CHAP_MD5
    - PAP
    description: The RADIUS protocol to use when authenticating.
  radius_timeout:
    required: false
    type: int
    default: 5
    choices: []
    description: The timeout (in seconds) for connections to this RADIUS authentication
      server.
  radius_nasip_attribute:
    required: true
    type: str
    default: null
    choices: []
    description: The interface whose IP will be used as the 'NAS-IP-Address' attribute
      during RADIUS Access-Requests. This choice will not change the interface used
      for contacting the RADIUS server.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "state": {
            "type": str,
            "required": False,
            "default": 'present',
            "choices": ['present', 'absent'],
        },
        "lookup_fields": {
            "type": list,
            "required": False,
            "default": None,
            "choices": [],
            "elements": "str",
            "suboptions": {},
        },
        "type": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['ldap', 'radius'],
        },
        "name": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "ldap_port": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "ldap_urltype": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['Standard TCP', 'STARTTLS Encrypt', 'SSL/TLS Encrypted'],
        },
        "ldap_protver": {
            "type": int,
            "required": False,
            "default": 3,
            "choices": [2, 3],
        },
        "ldap_timeout": {
            "type": int,
            "required": False,
            "default": 25,
            "choices": [],
        },
        "ldap_caref": {
            "type": str,
            "required": False,
            "default": 'global',
            "choices": [],
        },
        "ldap_scope": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['one', 'subtree'],
        },
        "ldap_basedn": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "ldap_authcn": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "ldap_extended_enabled": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ldap_extended_query": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "ldap_binddn": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "ldap_bindpw": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "ldap_attr_user": {
            "type": str,
            "required": False,
            "default": 'cn',
            "choices": [],
        },
        "ldap_attr_group": {
            "type": str,
            "required": False,
            "default": 'cn',
            "choices": [],
        },
        "ldap_attr_member": {
            "type": str,
            "required": False,
            "default": 'member',
            "choices": [],
        },
        "ldap_rfc2307": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ldap_rfc2307_userdn": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ldap_attr_groupobj": {
            "type": str,
            "required": False,
            "default": 'posixGroup',
            "choices": [],
        },
        "ldap_pam_groupdn": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "ldap_utf8": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ldap_nostrip_at": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "ldap_allow_unauthenticated": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "radius_secret": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "radius_auth_port": {
            "type": str,
            "required": False,
            "default": '1812',
            "choices": [],
        },
        "radius_acct_port": {
            "type": str,
            "required": False,
            "default": '1813',
            "choices": [],
        },
        "radius_protocol": {
            "type": str,
            "required": False,
            "default": 'MSCHAPv2',
            "choices": ['MSCHAPv2', 'MSCHAPv1', 'CHAP_MD5', 'PAP'],
        },
        "radius_timeout": {
            "type": int,
            "required": False,
            "default": 5,
            "choices": [],
        },
        "radius_nasip_attribute": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    client = rest.RestClient(
        host=module.params['api_host'],
        port=module.params['api_port'],
        username=module.params['api_username'],
        password=module.params['api_password'],
        api_key=module.params['api_key'],
        validate_certs=module.params['validate_certs']
    )

    base_module = base.BaseModule(client)
    changed, data = base_module.set_object_state(
        state=module.params['state'],
        data=module.params,
        lookup_fields=module.params['lookup_fields']
    )

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if resp['status'] != 200:
        module.fail_json(msg=resp['message'], **resp)

    result = {'changed': changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()