#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/vpn/openvpn/server."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: vpn_openvpn_server
description:
- Manage individual Open VPN Servers.
short_description: Manage individual Open VPN Servers.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: true
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource.
  description:
    required: false
    type: str
    default: ''
    choices: []
    description: The description for this OpenVPN server.
  disable:
    required: false
    type: bool
    default: false
    choices: []
    description: Disables this OpenVPN server.
  mode:
    required: true
    type: str
    default: null
    choices:
    - p2p_tls
    - server_tls
    - server_user
    - server_tls_user
    description: The OpenVPN server mode.
  authmode:
    required: false
    type: list
    default:
    - Local Database
    choices: []
    description: The name of the authentication server to use as the authentication
      backend for this OpenVPN server
    elements: str
  dev_mode:
    required: true
    type: str
    default: null
    choices:
    - tun
    - tap
    description: The carrier mode for this OpenVPN server. `tun` mode carries IPv4
      and IPv6 (layer 3) and is the most common and compatible mode across all platforms.
      `tap` mode is capable of carrying 802.3 (layer 2).
  protocol:
    required: true
    type: str
    default: null
    choices:
    - UDP4
    - UDP6
    - UDP
    - TCP4
    - TCP6
    - TCP
    description: The protocol used by this OpenVPN server.
  interface:
    required: false
    type: str
    default: null
    choices: []
    description: The interface or Virtual IP address where OpenVPN will receive client
      connections.
  local_port:
    required: false
    type: str
    default: '1194'
    choices: []
    description: 'The port used by OpenVPN to receive client connections. Valid options
      are: a TCP/UDP port number'
  use_tls:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the use of a TLS key for this OpenVPN server.
  tls:
    required: false
    type: str
    default: null
    choices: []
    description: The TLS key this OpenVPN server will use to sign control channel
      packets with an HMAC signature for authentication when establishing the tunnel.
  tls_type:
    required: false
    type: str
    default: null
    choices:
    - auth
    - crypt
    description: The TLS key usage type. In `auth` mode, the TLS key is used only
      as HMAC authentication for the control channel, protecting the peers from unauthorized
      connections. The `crypt` mode encrypts the control channel communication in
      addition to providing authentication, providing more privacy and traffic control
      channel obfuscation.
  tlsauth_keydir:
    required: false
    type: str
    default: default
    choices:
    - default
    - '0'
    - '1'
    - '2'
    description: The TLS key direction. This must be set to complementary values on
      the client and server. For example, if the server is set to 0, the client must
      be set to 1. Both may be set to omit the direction, in which case the TLS Key
      will be used bidirectionally.
  caref:
    required: true
    type: str
    default: null
    choices: []
    description: The `refid` of the CA object to assume as the peer CA.
  certref:
    required: true
    type: str
    default: null
    choices: []
    description: The `refid` of the certificate object to assume as the OpenVPN server
      certificate.
  cert_depth:
    required: false
    type: int
    default: 1
    choices:
    - 1
    - 2
    - 3
    - 4
    - 5
    description: The depth of the certificate chain to check when a certificate based
      client signs in. Certificates below this depth are not accepted. This is useful
      for denying certificates made with intermediate CAs generated from the same
      CA as the server. Set to null to use system default.
  dh_length:
    required: true
    type: str
    default: null
    choices: []
    description: The Diffie-Hellman (DH) parameter set used for key exchange.
  ecdh_curve:
    required: true
    type: str
    default: null
    choices: []
    description: The Elliptic Curve to use for key exchange. The curve from the server
      certificate is used by default when the server uses an ECDSA certificate. Otherwise,
      secp384r1 is used as a fallback.
  data_ciphers:
    required: true
    type: list
    default: null
    choices: []
    description: The encryption algorithms/ciphers allowed by this OpenVPN server.
    elements: str
  data_ciphers_fallback:
    required: true
    type: str
    default: null
    choices: []
    description: The fallback encryption algorithm/cipher used for data channel packets
      when communicating with clients that do not support data encryption algorithm
      negotiation (e.g. Shared Key).
  digest:
    required: true
    type: str
    default: null
    choices: []
    description: The algorithm used to authenticate data channel packets, and control
      channel packets if a TLS Key is present.
  strictusercn:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables enforcing a match between the common name of
      the client certificate and the username given at login.
  remote_cert_tls:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables requiring hosts to have a client certificate
      to connect.
  tunnel_network:
    required: false
    type: str
    default: ''
    choices: []
    description: The IPv4 virtual network used for private communications between
      this server and client hosts.
  tunnel_networkv6:
    required: false
    type: str
    default: ''
    choices: []
    description: The IPv6 virtual network used for private communications between
      this server and client hosts.
  serverbridge_dhcp:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables clients on the bridge to obtain DHCP.
  serverbridge_interface:
    required: false
    type: str
    default: null
    choices: []
    description: The interface to which this TAP instance will be bridged. This is
      not done automatically. This interface must be assigned and the bridge created
      separately. This setting controls which existing IP address and subnet mask
      are used by OpenVPN for the bridge.
  serverbridge_routegateway:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables pushing the bridge interface's IPv4 address to
      connecting clients as a route gateway.
  serverbridge_dhcp_start:
    required: false
    type: str
    default: null
    choices: []
    description: The bridge DHCP range's start address.
  serverbridge_dhcp_end:
    required: false
    type: str
    default: null
    choices: []
    description: The bridge DHCP range's end address.
  gwredir:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable forcing all client-generated IPv4 traffic through the tunnel.
  gwredir6:
    required: false
    type: bool
    default: false
    choices: []
    description: Enable forcing all client-generated IPv6 traffic through the tunnel.
  local_network:
    required: false
    type: list
    default: []
    choices: []
    description: The IPv4 networks that will be accessible from the remote endpoint.
      Expressed as a list of one or more CIDR ranges or host/network type aliases.
      This may be left blank if not adding a route to the local network through this
      tunnel on the remote machine. This is generally set to the LAN network.
    elements: str
  local_networkv6:
    required: false
    type: list
    default: []
    choices: []
    description: The IPv6 networks that will be accessible from the remote endpoint.
      Expressed as a list of one or more CIDR ranges or host/network type aliases.
      This may be left blank if not adding a route to the local network through this
      tunnel on the remote machine. This is generally set to the LAN network.
    elements: str
  remote_network:
    required: false
    type: list
    default: []
    choices: []
    description: IPv4 networks that will be routed through the tunnel, so that a site-to-site
      VPN can be established without manually changing the routing tables. Expressed
      as a list of one or more CIDR ranges or host/network type aliases. If this is
      a site-to-site VPN, enter the remote LAN/s here. May be left empty for non site-to-site
      VPN.
    elements: str
  remote_networkv6:
    required: false
    type: list
    default: []
    choices: []
    description: IPv6 networks that will be routed through the tunnel, so that a site-to-site
      VPN can be established without manually changing the routing tables. Expressed
      as a list of one or more CIDR ranges or host/network type aliases. If this is
      a site-to-site VPN, enter the remote LAN/s here. May be left empty for non site-to-site
      VPN.
    elements: str
  maxclients:
    required: false
    type: int
    default: null
    choices: []
    description: The maximum number of clients allowed to concurrently connect to
      this server.
  allow_compression:
    required: false
    type: str
    default: 'no'
    choices:
    - 'no'
    - 'yes'
    - asym
    description: The compression mode allowed by this OpenVPN server. Compression
      can potentially increase throughput but may allow an attacker to extract secrets
      if they can control compressed plaintext traversing the VPN (e.g. HTTP)
  passtos:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables setting the TOS IP header value of tunnel packets
      to match the encapsulated packet value.
  client2client:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables allowing communication between clients connected
      to this server.
  duplicate_cn:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disable allowing the same user to connect multiple times.
  connlimit:
    required: false
    type: int
    default: null
    choices: []
    description: The number of concurrent connections a single user can have.
  dynamic_ip:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables allowing connected clients to retain their connections
      if their IP address changes.
  topology:
    required: false
    type: str
    default: subnet
    choices:
    - subnet
    - net30
    description: The method used to supply a virtual adapter IP address to clients
      when using TUN mode on IPv4.
  inactive_seconds:
    required: false
    type: int
    default: 300
    choices: []
    description: The amount of time (in seconds) until a client connection is closed
      for inactivity.
  ping_method:
    required: false
    type: str
    default: keepalive
    choices:
    - keepalive
    - ping
    description: The method used to define ping configuration.
  keepalive_interval:
    required: false
    type: int
    default: 10
    choices: []
    description: The keepalive interval parameter.
  keepalive_timeout:
    required: false
    type: int
    default: 60
    choices: []
    description: The keepalive timeout parameter.
  ping_seconds:
    required: false
    type: int
    default: 10
    choices: []
    description: The number of seconds to accept no packets before sending a ping
      to the remote peer over the TCP/UDP control channel.
  ping_push:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables push ping to the VPN client.
  ping_action:
    required: false
    type: str
    default: ping_restart
    choices:
    - ping_restart
    - ping_exit
    description: The action to take after a ping to the remote peer times-out.
  ping_action_seconds:
    required: false
    type: int
    default: 60
    choices: []
    description: The number of seconds that must elapse before the ping is considered
      a timeout and the configured `ping_action` is performed.
  ping_action_push:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables pushing the ping action to the VPN client.
  dns_domain:
    required: false
    type: str
    default: ''
    choices: []
    description: The default domain to provide to clients.
  dns_server1:
    required: false
    type: str
    default: ''
    choices: []
    description: The primary DNS server to provide to clients.
  dns_server2:
    required: false
    type: str
    default: ''
    choices: []
    description: The secondary DNS server to provide to clients.
  dns_server3:
    required: false
    type: str
    default: ''
    choices: []
    description: The tertiary DNS server to provide to clients.
  dns_server4:
    required: false
    type: str
    default: ''
    choices: []
    description: The quaternary DNS server to provide to clients.
  push_blockoutsidedns:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables blocking Windows 10 clients' access to DNS servers
      except across OpenVPN while connected, forcing clients to use only VPN DNS servers.
  push_register_dns:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables running `net stop dnscache`, `net start dnscache`,
      `ipconfig /flushdns` and `ipconfig /registerdns` on connection initiation for
      Windows clients.
  ntp_server1:
    required: false
    type: str
    default: ''
    choices: []
    description: The primary NTP server to provide to clients.
  ntp_server2:
    required: false
    type: str
    default: ''
    choices: []
    description: The secondary NTP server to provide to clients.
  netbios_enable:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables NetBIOS over TCP/IP.
  netbios_ntype:
    required: false
    type: int
    default: 0
    choices:
    - 0
    - 1
    - 2
    - 4
    - 8
    description: The NetBIOS node type.
  netbios_scope:
    required: false
    type: str
    default: ''
    choices: []
    description: The NetBIOS Scope ID. This provides an extended naming service for
      NetBIOS over TCP/IP. The NetBIOS scope ID isolates NetBIOS traffic on a single
      network to only those nodes with the same NetBIOS scope ID.
  wins_server1:
    required: false
    type: str
    default: ''
    choices: []
    description: The primary WINS server to provide to clients.
  wins_server2:
    required: false
    type: str
    default: ''
    choices: []
    description: The secondary WINS server to provide to clients.
  custom_options:
    required: false
    type: list
    default: []
    choices: []
    description: Additional options to add to the OpenVPN server configuration.
    elements: str
  username_as_common_name:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disable the username of the client being used in place
      of the certificate common name for purposes such as determining Client Specific
      Overrides.
  sndrcvbuf:
    required: false
    type: int
    default: null
    choices:
    - 65536
    - 131072
    - 262144
    - 524288
    - 1048576
    - 2097152
    description: The send and receive buffer size for OpenVPN. Set to null to use
      the system default.
  create_gw:
    required: false
    type: str
    default: both
    choices:
    - both
    - v4only
    - v6only
    description: The gateway type(s) that will be created when a virtual interface
      is assigned to this OpenVPN server
  verbosity_level:
    required: false
    type: int
    default: 1
    choices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    description: The OpenVPN logging verbosity level.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Create Open VPN Server
  pfrest.pfsense.vpn_openvpn_server:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: present
    mode: p2p_tls
    dev_mode: tun
    protocol: UDP4
    interface: string
    tls_type: auth
    caref: string
    certref: string
    dh_length: string
    ecdh_curve: string
    data_ciphers: &id001
    - string
    data_ciphers_fallback: string
    digest: string
    serverbridge_interface: string
    serverbridge_dhcp_start: string
    serverbridge_dhcp_end: string
- name: Delete Open VPN Server
  pfrest.pfsense.vpn_openvpn_server:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: absent
    mode: p2p_tls
    dev_mode: tun
    protocol: UDP4
    interface: string
    tls_type: auth
    caref: string
    certref: string
    dh_length: string
    ecdh_curve: string
    data_ciphers: *id001
    data_ciphers_fallback: string
    digest: string
    serverbridge_interface: string
    serverbridge_dhcp_start: string
    serverbridge_dhcp_end: string

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Open VPN Server data returned by the API.
  type: dict
  returned: always
  contains:
    vpnid:
      description: The unique ID for this OpenVPN server. This value is assigned by
        the system and cannot be changed.
      type: int
      returned: always
    vpnif:
      description: The VPN interface name for this OpenVPN server. This value is assigned
        by the system and cannot be changed.
      type: str
      returned: always
    description:
      description: The description for this OpenVPN server.
      type: str
      returned: always
    disable:
      description: Disables this OpenVPN server.
      type: bool
      returned: always
    mode:
      description: The OpenVPN server mode.
      type: str
      returned: always
    authmode:
      description: The name of the authentication server to use as the authentication
        backend for this OpenVPN server
      type: list
      returned: always
      elements: str
    dev_mode:
      description: The carrier mode for this OpenVPN server. `tun` mode carries IPv4
        and IPv6 (layer 3) and is the most common and compatible mode across all platforms.
        `tap` mode is capable of carrying 802.3 (layer 2).
      type: str
      returned: always
    protocol:
      description: The protocol used by this OpenVPN server.
      type: str
      returned: always
    interface:
      description: The interface or Virtual IP address where OpenVPN will receive
        client connections.
      type: str
      returned: always
    local_port:
      description: 'The port used by OpenVPN to receive client connections. Valid
        options are: a TCP/UDP port number'
      type: str
      returned: always
    use_tls:
      description: Enables or disables the use of a TLS key for this OpenVPN server.
      type: bool
      returned: always
    tls:
      description: The TLS key this OpenVPN server will use to sign control channel
        packets with an HMAC signature for authentication when establishing the tunnel.
      type: str
      returned: always
    tls_type:
      description: The TLS key usage type. In `auth` mode, the TLS key is used only
        as HMAC authentication for the control channel, protecting the peers from
        unauthorized connections. The `crypt` mode encrypts the control channel communication
        in addition to providing authentication, providing more privacy and traffic
        control channel obfuscation.
      type: str
      returned: always
    tlsauth_keydir:
      description: The TLS key direction. This must be set to complementary values
        on the client and server. For example, if the server is set to 0, the client
        must be set to 1. Both may be set to omit the direction, in which case the
        TLS Key will be used bidirectionally.
      type: str
      returned: always
    caref:
      description: The `refid` of the CA object to assume as the peer CA.
      type: str
      returned: always
    certref:
      description: The `refid` of the certificate object to assume as the OpenVPN
        server certificate.
      type: str
      returned: always
    cert_depth:
      description: The depth of the certificate chain to check when a certificate
        based client signs in. Certificates below this depth are not accepted. This
        is useful for denying certificates made with intermediate CAs generated from
        the same CA as the server. Set to null to use system default.
      type: int
      returned: always
    dh_length:
      description: The Diffie-Hellman (DH) parameter set used for key exchange.
      type: str
      returned: always
    ecdh_curve:
      description: The Elliptic Curve to use for key exchange. The curve from the
        server certificate is used by default when the server uses an ECDSA certificate.
        Otherwise, secp384r1 is used as a fallback.
      type: str
      returned: always
    data_ciphers:
      description: The encryption algorithms/ciphers allowed by this OpenVPN server.
      type: list
      returned: always
      elements: str
    data_ciphers_fallback:
      description: The fallback encryption algorithm/cipher used for data channel
        packets when communicating with clients that do not support data encryption
        algorithm negotiation (e.g. Shared Key).
      type: str
      returned: always
    digest:
      description: The algorithm used to authenticate data channel packets, and control
        channel packets if a TLS Key is present.
      type: str
      returned: always
    strictusercn:
      description: Enables or disables enforcing a match between the common name of
        the client certificate and the username given at login.
      type: bool
      returned: always
    remote_cert_tls:
      description: Enables or disables requiring hosts to have a client certificate
        to connect.
      type: bool
      returned: always
    tunnel_network:
      description: The IPv4 virtual network used for private communications between
        this server and client hosts.
      type: str
      returned: always
    tunnel_networkv6:
      description: The IPv6 virtual network used for private communications between
        this server and client hosts.
      type: str
      returned: always
    serverbridge_dhcp:
      description: Enables or disables clients on the bridge to obtain DHCP.
      type: bool
      returned: always
    serverbridge_interface:
      description: The interface to which this TAP instance will be bridged. This
        is not done automatically. This interface must be assigned and the bridge
        created separately. This setting controls which existing IP address and subnet
        mask are used by OpenVPN for the bridge.
      type: str
      returned: always
    serverbridge_routegateway:
      description: Enables or disables pushing the bridge interface's IPv4 address
        to connecting clients as a route gateway.
      type: bool
      returned: always
    serverbridge_dhcp_start:
      description: The bridge DHCP range's start address.
      type: str
      returned: always
    serverbridge_dhcp_end:
      description: The bridge DHCP range's end address.
      type: str
      returned: always
    gwredir:
      description: Enable forcing all client-generated IPv4 traffic through the tunnel.
      type: bool
      returned: always
    gwredir6:
      description: Enable forcing all client-generated IPv6 traffic through the tunnel.
      type: bool
      returned: always
    local_network:
      description: The IPv4 networks that will be accessible from the remote endpoint.
        Expressed as a list of one or more CIDR ranges or host/network type aliases.
        This may be left blank if not adding a route to the local network through
        this tunnel on the remote machine. This is generally set to the LAN network.
      type: list
      returned: always
      elements: str
    local_networkv6:
      description: The IPv6 networks that will be accessible from the remote endpoint.
        Expressed as a list of one or more CIDR ranges or host/network type aliases.
        This may be left blank if not adding a route to the local network through
        this tunnel on the remote machine. This is generally set to the LAN network.
      type: list
      returned: always
      elements: str
    remote_network:
      description: IPv4 networks that will be routed through the tunnel, so that a
        site-to-site VPN can be established without manually changing the routing
        tables. Expressed as a list of one or more CIDR ranges or host/network type
        aliases. If this is a site-to-site VPN, enter the remote LAN/s here. May be
        left empty for non site-to-site VPN.
      type: list
      returned: always
      elements: str
    remote_networkv6:
      description: IPv6 networks that will be routed through the tunnel, so that a
        site-to-site VPN can be established without manually changing the routing
        tables. Expressed as a list of one or more CIDR ranges or host/network type
        aliases. If this is a site-to-site VPN, enter the remote LAN/s here. May be
        left empty for non site-to-site VPN.
      type: list
      returned: always
      elements: str
    maxclients:
      description: The maximum number of clients allowed to concurrently connect to
        this server.
      type: int
      returned: always
    allow_compression:
      description: The compression mode allowed by this OpenVPN server. Compression
        can potentially increase throughput but may allow an attacker to extract secrets
        if they can control compressed plaintext traversing the VPN (e.g. HTTP)
      type: str
      returned: always
    passtos:
      description: Enables or disables setting the TOS IP header value of tunnel packets
        to match the encapsulated packet value.
      type: bool
      returned: always
    client2client:
      description: Enables or disables allowing communication between clients connected
        to this server.
      type: bool
      returned: always
    duplicate_cn:
      description: Enables or disable allowing the same user to connect multiple times.
      type: bool
      returned: always
    connlimit:
      description: The number of concurrent connections a single user can have.
      type: int
      returned: always
    dynamic_ip:
      description: Enables or disables allowing connected clients to retain their
        connections if their IP address changes.
      type: bool
      returned: always
    topology:
      description: The method used to supply a virtual adapter IP address to clients
        when using TUN mode on IPv4.
      type: str
      returned: always
    inactive_seconds:
      description: The amount of time (in seconds) until a client connection is closed
        for inactivity.
      type: int
      returned: always
    ping_method:
      description: The method used to define ping configuration.
      type: str
      returned: always
    keepalive_interval:
      description: The keepalive interval parameter.
      type: int
      returned: always
    keepalive_timeout:
      description: The keepalive timeout parameter.
      type: int
      returned: always
    ping_seconds:
      description: The number of seconds to accept no packets before sending a ping
        to the remote peer over the TCP/UDP control channel.
      type: int
      returned: always
    ping_push:
      description: Enables or disables push ping to the VPN client.
      type: bool
      returned: always
    ping_action:
      description: The action to take after a ping to the remote peer times-out.
      type: str
      returned: always
    ping_action_seconds:
      description: The number of seconds that must elapse before the ping is considered
        a timeout and the configured `ping_action` is performed.
      type: int
      returned: always
    ping_action_push:
      description: Enables or disables pushing the ping action to the VPN client.
      type: bool
      returned: always
    dns_domain:
      description: The default domain to provide to clients.
      type: str
      returned: always
    dns_server1:
      description: The primary DNS server to provide to clients.
      type: str
      returned: always
    dns_server2:
      description: The secondary DNS server to provide to clients.
      type: str
      returned: always
    dns_server3:
      description: The tertiary DNS server to provide to clients.
      type: str
      returned: always
    dns_server4:
      description: The quaternary DNS server to provide to clients.
      type: str
      returned: always
    push_blockoutsidedns:
      description: Enables or disables blocking Windows 10 clients' access to DNS
        servers except across OpenVPN while connected, forcing clients to use only
        VPN DNS servers.
      type: bool
      returned: always
    push_register_dns:
      description: Enables or disables running `net stop dnscache`, `net start dnscache`,
        `ipconfig /flushdns` and `ipconfig /registerdns` on connection initiation
        for Windows clients.
      type: bool
      returned: always
    ntp_server1:
      description: The primary NTP server to provide to clients.
      type: str
      returned: always
    ntp_server2:
      description: The secondary NTP server to provide to clients.
      type: str
      returned: always
    netbios_enable:
      description: Enables or disables NetBIOS over TCP/IP.
      type: bool
      returned: always
    netbios_ntype:
      description: The NetBIOS node type.
      type: int
      returned: always
    netbios_scope:
      description: The NetBIOS Scope ID. This provides an extended naming service
        for NetBIOS over TCP/IP. The NetBIOS scope ID isolates NetBIOS traffic on
        a single network to only those nodes with the same NetBIOS scope ID.
      type: str
      returned: always
    wins_server1:
      description: The primary WINS server to provide to clients.
      type: str
      returned: always
    wins_server2:
      description: The secondary WINS server to provide to clients.
      type: str
      returned: always
    custom_options:
      description: Additional options to add to the OpenVPN server configuration.
      type: list
      returned: always
      elements: str
    username_as_common_name:
      description: Enables or disable the username of the client being used in place
        of the certificate common name for purposes such as determining Client Specific
        Overrides.
      type: bool
      returned: always
    sndrcvbuf:
      description: The send and receive buffer size for OpenVPN. Set to null to use
        the system default.
      type: int
      returned: always
    create_gw:
      description: The gateway type(s) that will be created when a virtual interface
        is assigned to this OpenVPN server
      type: str
      returned: always
    verbosity_level:
      description: The OpenVPN logging verbosity level.
      type: int
      returned: always

"""


def run_module():
    """Runs this resource module against /api/v2/vpn/openvpn/server."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "state": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "present",
            "choices": ["present", "absent"],
        },
        "lookup_fields": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "str",
        },
        "description": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "disable": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "mode": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
            "choices": ["p2p_tls", "server_tls", "server_user", "server_tls_user"],
        },
        "authmode": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": ["Local Database"],
            "elements": "str",
        },
        "dev_mode": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
            "choices": ["tun", "tap"],
        },
        "protocol": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
            "choices": ["UDP4", "UDP6", "UDP", "TCP4", "TCP6", "TCP"],
        },
        "interface": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "local_port": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "1194",
        },
        "use_tls": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "tls": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": None,
        },
        "tls_type": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "choices": ["auth", "crypt"],
        },
        "tlsauth_keydir": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "default",
            "choices": ["default", "0", "1", "2"],
        },
        "caref": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "certref": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "cert_depth": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 1,
            "choices": [1, 2, 3, 4, 5],
        },
        "dh_length": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "ecdh_curve": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "data_ciphers": {
            "type": "list",
            "required": True,
            "no_log": False,
            "default": None,
            "elements": "str",
        },
        "data_ciphers_fallback": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "digest": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
        },
        "strictusercn": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "remote_cert_tls": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "tunnel_network": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "tunnel_networkv6": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "serverbridge_dhcp": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "serverbridge_interface": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "serverbridge_routegateway": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "serverbridge_dhcp_start": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "serverbridge_dhcp_end": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "gwredir": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "gwredir6": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "local_network": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
        },
        "local_networkv6": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
        },
        "remote_network": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
        },
        "remote_networkv6": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
        },
        "maxclients": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "allow_compression": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "no",
            "choices": ["no", "yes", "asym"],
        },
        "passtos": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "client2client": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "duplicate_cn": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "connlimit": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
        },
        "dynamic_ip": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "topology": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "subnet",
            "choices": ["subnet", "net30"],
        },
        "inactive_seconds": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 300,
        },
        "ping_method": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "keepalive",
            "choices": ["keepalive", "ping"],
        },
        "keepalive_interval": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 10,
        },
        "keepalive_timeout": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 60,
        },
        "ping_seconds": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 10,
        },
        "ping_push": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "ping_action": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "ping_restart",
            "choices": ["ping_restart", "ping_exit"],
        },
        "ping_action_seconds": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 60,
        },
        "ping_action_push": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "dns_domain": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "dns_server1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "dns_server2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "dns_server3": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "dns_server4": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "push_blockoutsidedns": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "push_register_dns": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "ntp_server1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "ntp_server2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "netbios_enable": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "netbios_ntype": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 0,
            "choices": [0, 1, 2, 4, 8],
        },
        "netbios_scope": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "wins_server1": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "wins_server2": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
        },
        "custom_options": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": [],
            "elements": "str",
        },
        "username_as_common_name": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
        },
        "sndrcvbuf": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "choices": [65536, 131072, 262144, 524288, 1048576, 2097152],
        },
        "create_gw": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "both",
            "choices": ["both", "v4only", "v6only"],
        },
        "verbosity_level": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 1,
            "choices": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/vpn/openvpn/server", client)
    changed, resp = base_module.set_object_state(
        state=module.params["state"],
        data=module.params,
        lookup_fields=module.params["lookup_fields"],
        parent_lookup_fields=module.params.get("parent_lookup_fields", []),
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
