#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/generate_module.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generate.conf FILE.
###############################################################

from ansible.module_utils.basic import AnsibleModule

DOCUMENTATION = '''
module: vpn_openvpn_client
description:
- Manage individual Open VPN Clients.
short_description: Manage individual Open VPN Clients.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: 'The port number of the pfSense API (default: 443).'
  api_username:
    type: str
    default: admin
    description: 'The username to authenticate with the pfSense API. (default: ''admin'')'
  api_password:
    type: str
    default: pfsense
    no_log: true
    description: 'The password to authenticate with the pfSense API. (default: ''pfsense'')'
  api_key:
    type: str
    no_log: true
    description: An optional API key for authentication instead of username/password.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  description:
    required: false
    type: str
    default: ''
    choices: []
    description: The description for this OpenVPN client.
  disable:
    required: false
    type: bool
    default: false
    choices: []
    description: Disables this OpenVPN client.
  mode:
    required: true
    type: str
    default: null
    choices:
    - p2p_tls
    description: The OpenVPN client mode.
  dev_mode:
    required: true
    type: str
    default: null
    choices:
    - tun
    - tap
    description: The carrier mode for this OpenVPN client. `tun` mode carries IPv4
      and IPv6 (layer 3) and is the most common and compatible mode across all platforms.
      `tap` mode is capable of carrying 802.3 (layer 2).
  protocol:
    required: true
    type: str
    default: null
    choices:
    - UDP4
    - UDP6
    - UDP
    - TCP4
    - TCP6
    - TCP
    description: The protocol used by this OpenVPN client.
  interface:
    required: true
    type: str
    default: null
    choices: []
    description: The interface used by the firewall to originate this OpenVPN client
      connection.
  server_addr:
    required: true
    type: str
    default: null
    choices: []
    description: The IP address or hostname of the OpenVPN server this client will
      connect to.
  server_port:
    required: true
    type: str
    default: null
    choices: []
    description: 'The port used by the server to receive client connections. Valid
      options are: a TCP/UDP port number'
  local_port:
    required: false
    type: str
    default: null
    choices: []
    description: 'The port binding used by OpenVPN for client connections. Valid options
      are: a TCP/UDP port number'
  proxy_addr:
    required: false
    type: str
    default: null
    choices: []
    description: The address for an HTTP Proxy this client can use to connect to a
      remote server.
  proxy_port:
    required: false
    type: str
    default: null
    choices: []
    description: 'The port used by the HTTP Proxy. Valid options are: a TCP/UDP port
      number'
  proxy_authtype:
    required: false
    type: str
    default: none
    choices:
    - none
    - basic
    - ntlm
    description: The type of authentication used by the proxy server.
  proxy_user:
    required: true
    type: str
    default: null
    choices: []
    description: The username to use for authentication to the remote proxy.
  proxy_passwd:
    required: true
    type: str
    default: null
    choices: []
    description: The username to use for authentication to the remote proxy.
  auth_user:
    required: false
    type: str
    default: null
    choices: []
    description: The username used to authenticate with the OpenVPN server.
  auth_pass:
    required: false
    type: str
    default: null
    choices: []
    description: The password used to authenticate with the OpenVPN server.
  auth_retry_none:
    required: false
    type: bool
    default: false
    choices: []
    description: Disables retrying authentication if an authentication failed error
      is received from the server
  tls:
    required: false
    type: str
    default: null
    choices: []
    description: The TLS key this OpenVPN client will use to sign control channel
      packets with an HMAC signature for authentication when establishing the tunnel.
  tls_type:
    required: true
    type: str
    default: null
    choices:
    - auth
    - crypt
    description: The TLS key usage type. In `auth` mode, the TLS key is used only
      as HMAC authentication for the control channel, protecting the peers from unauthorized
      connections. The `crypt` mode encrypts the control channel communication in
      addition to providing authentication, providing more privacy and traffic control
      channel obfuscation.
  tlsauth_keydir:
    required: false
    type: str
    default: default
    choices:
    - default
    - '0'
    - '1'
    - '2'
    description: The TLS key direction. This must be set to complementary values on
      the client and client. For example, if the client is set to 0, the client must
      be set to 1. Both may be set to omit the direction, in which case the TLS Key
      will be used bidirectionally.
  caref:
    required: true
    type: str
    default: null
    choices: []
    description: The `refid` of the CA object to assume as the peer CA.
  certref:
    required: false
    type: str
    default: null
    choices: []
    description: The `refid` of the certificate object to assume as the OpenVPN client
      certificate.
  data_ciphers:
    required: true
    type: str
    default: null
    choices: []
    description: The encryption algorithms/ciphers allowed by this OpenVPN client.
  data_ciphers_fallback:
    required: true
    type: str
    default: null
    choices: []
    description: The fallback encryption algorithm/cipher used for data channel packets
      when communicating with clients that do not support data encryption algorithm
      negotiation (e.g. Shared Key).
  digest:
    required: true
    type: str
    default: null
    choices: []
    description: The algorithm used to authenticate data channel packets, and control
      channel packets if a TLS Key is present.
  remote_cert_tls:
    required: false
    type: bool
    default: true
    choices: []
    description: Enables or disables requiring hosts to have a client certificate
      to connect.
  tunnel_network:
    required: false
    type: str
    default: ''
    choices: []
    description: The IPv4 virtual network used for private communications between
      this client and client hosts.
  tunnel_networkv6:
    required: false
    type: str
    default: ''
    choices: []
    description: The IPv6 virtual network used for private communications between
      this client and client hosts.
  remote_network:
    required: false
    type: str
    default: []
    choices: []
    description: IPv4 networks that will be routed through the tunnel, so that a site-to-site
      VPN can be established without manually changing the routing tables. Expressed
      as a list of one or more CIDR ranges or host/network type aliases. If this is
      a site-to-site VPN, enter the remote LAN/s here. May be left empty for non site-to-site
      VPN.
  remote_networkv6:
    required: false
    type: str
    default: []
    choices: []
    description: IPv6 networks that will be routed through the tunnel, so that a site-to-site
      VPN can be established without manually changing the routing tables. Expressed
      as a list of one or more CIDR ranges or host/network type aliases. If this is
      a site-to-site VPN, enter the remote LAN/s here. May be left empty for non site-to-site
      VPN.
  use_shaper:
    required: false
    type: int
    default: null
    choices: []
    description: Maximum outgoing bandwidth (in bytes per second) for this tunnel.
      Use `null` no limit.
  allow_compression:
    required: false
    type: str
    default: 'no'
    choices:
    - 'no'
    - 'yes'
    - asym
    description: The compression mode allowed by this OpenVPN client. Compression
      can potentially increase throughput but may allow an attacker to extract secrets
      if they can control compressed plaintext traversing the VPN (e.g. HTTP)
  passtos:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables setting the TOS IP header value of tunnel packets
      to match the encapsulated packet value.
  route_no_pull:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables the servers ability to add routes to the client's
      routing table.
  route_no_exec:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables adding/removing routes automatically.
  dns_add:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables using the DNS server(s) provided by the OpenVPN
      server.
  topology:
    required: false
    type: str
    default: subnet
    choices:
    - subnet
    - net30
    description: The method used to supply a virtual adapter IP address to clients
      when using TUN mode on IPv4.
  inactive_seconds:
    required: false
    type: int
    default: 300
    choices: []
    description: The amount of time (in seconds) until a client connection is closed
      for inactivity.
  ping_method:
    required: false
    type: str
    default: keepalive
    choices:
    - keepalive
    - ping
    description: The method used to define ping configuration.
  keepalive_interval:
    required: false
    type: int
    default: 10
    choices: []
    description: The keepalive interval parameter.
  keepalive_timeout:
    required: false
    type: int
    default: 60
    choices: []
    description: The keepalive timeout parameter.
  ping_seconds:
    required: false
    type: int
    default: 10
    choices: []
    description: The number of seconds to accept no packets before sending a ping
      to the remote peer over the TCP/UDP control channel.
  ping_action:
    required: false
    type: str
    default: ping_restart
    choices:
    - ping_restart
    - ping_exit
    description: The action to take after a ping to the remote peer times-out.
  ping_action_seconds:
    required: false
    type: int
    default: 60
    choices: []
    description: The number of seconds that must elapse before the ping is considered
      a timeout and the configured `ping_action` is performed.
  custom_options:
    required: false
    type: str
    default: []
    choices: []
    description: Additional options to add to the OpenVPN client configuration.
  udp_fast_io:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables fast I/O operations with UDP writes to tun/tap
      (Experimental).
  exit_notify:
    required: false
    type: str
    default: none
    choices:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - none
    description: The number of times this client will attempt to send an exit notifications.
  sndrcvbuf:
    required: false
    type: int
    default: null
    choices:
    - 65536
    - 131072
    - 262144
    - 524288
    - 1048576
    - 2097152
    description: The send and receive buffer size for OpenVPN. Set to null to use
      the system default.
  create_gw:
    required: false
    type: str
    default: both
    choices:
    - both
    - v4only
    - v6only
    description: The gateway type(s) that will be created when a virtual interface
      is assigned to this OpenVPN server
  verbosity_level:
    required: false
    type: int
    default: 1
    choices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    description: The OpenVPN logging verbosity level.
author:
- Jared Hendrickson (@jaredhendrickson13)

'''


def run_module():
    module_args = {
        "api_host": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "api_port": {
            "type": int,
            "required": False,
            "default": 443,
            "choices": [],
        },
        "api_username": {
            "type": str,
            "required": False,
            "default": 'admin',
            "choices": [],
        },
        "api_password": {
            "type": str,
            "required": False,
            "default": 'pfsense',
            "choices": [],
        },
        "api_key": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "validate_certs": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "description": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "disable": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "mode": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['p2p_tls'],
        },
        "dev_mode": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['tun', 'tap'],
        },
        "protocol": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['UDP4', 'UDP6', 'UDP', 'TCP4', 'TCP6', 'TCP'],
        },
        "interface": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "server_addr": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "server_port": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "local_port": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "proxy_addr": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "proxy_port": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "proxy_authtype": {
            "type": str,
            "required": False,
            "default": 'none',
            "choices": ['none', 'basic', 'ntlm'],
        },
        "proxy_user": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "proxy_passwd": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "auth_user": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "auth_pass": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "auth_retry_none": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "tls": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "tls_type": {
            "type": str,
            "required": True,
            "default": None,
            "choices": ['auth', 'crypt'],
        },
        "tlsauth_keydir": {
            "type": str,
            "required": False,
            "default": 'default',
            "choices": ['default', '0', '1', '2'],
        },
        "caref": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "certref": {
            "type": str,
            "required": False,
            "default": None,
            "choices": [],
        },
        "data_ciphers": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "data_ciphers_fallback": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "digest": {
            "type": str,
            "required": True,
            "default": None,
            "choices": [],
        },
        "remote_cert_tls": {
            "type": bool,
            "required": False,
            "default": True,
            "choices": [],
        },
        "tunnel_network": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "tunnel_networkv6": {
            "type": str,
            "required": False,
            "default": '',
            "choices": [],
        },
        "remote_network": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "remote_networkv6": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "use_shaper": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [],
        },
        "allow_compression": {
            "type": str,
            "required": False,
            "default": 'no',
            "choices": ['no', 'yes', 'asym'],
        },
        "passtos": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "route_no_pull": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "route_no_exec": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "dns_add": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "topology": {
            "type": str,
            "required": False,
            "default": 'subnet',
            "choices": ['subnet', 'net30'],
        },
        "inactive_seconds": {
            "type": int,
            "required": False,
            "default": 300,
            "choices": [],
        },
        "ping_method": {
            "type": str,
            "required": False,
            "default": 'keepalive',
            "choices": ['keepalive', 'ping'],
        },
        "keepalive_interval": {
            "type": int,
            "required": False,
            "default": 10,
            "choices": [],
        },
        "keepalive_timeout": {
            "type": int,
            "required": False,
            "default": 60,
            "choices": [],
        },
        "ping_seconds": {
            "type": int,
            "required": False,
            "default": 10,
            "choices": [],
        },
        "ping_action": {
            "type": str,
            "required": False,
            "default": 'ping_restart',
            "choices": ['ping_restart', 'ping_exit'],
        },
        "ping_action_seconds": {
            "type": int,
            "required": False,
            "default": 60,
            "choices": [],
        },
        "custom_options": {
            "type": str,
            "required": False,
            "default": [],
            "choices": [],
        },
        "udp_fast_io": {
            "type": bool,
            "required": False,
            "default": False,
            "choices": [],
        },
        "exit_notify": {
            "type": str,
            "required": False,
            "default": 'none',
            "choices": ['1', '2', '3', '4', '5', 'none'],
        },
        "sndrcvbuf": {
            "type": int,
            "required": False,
            "default": None,
            "choices": [65536, 131072, 262144, 524288, 1048576, 2097152],
        },
        "create_gw": {
            "type": str,
            "required": False,
            "default": 'both',
            "choices": ['both', 'v4only', 'v6only'],
        },
        "verbosity_level": {
            "type": int,
            "required": False,
            "default": 1,
            "choices": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        },
    }

    module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True
    )

    # TODO: Implement API logic here using module.params to access the parameters defined above.
    result = {'changed': True, 'original_message': module.params['name'], 'message': "API call successful"}
    module.exit_json(**result)


if __name__ == '__main__':
    run_module()