#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/vpn/openvpn/client_export/configs."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: vpn_openvpn_client_export_configs_info
description:
- Retrieve information about many Open VPN Client Export Configs.
short_description: Retrieve information about many Open VPN Client Export Configs.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  query_params:
    type: dict
    description: Optional query parameters for filtering the results.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve all Open VPN Client Export Configs
  pfrest.pfsense.vpn_openvpn_client_export_configs_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of Open VPN Client Export Configs returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    server:
      description: The VPN ID of the OpenVPN server this client export corresponds
        to.
      type: int
      returned: always
    useaddr:
      description: The method to use for the OpenVPN server address listed in the
        config export.
      type: str
      returned: always
    useaddr_hostname:
      description: The hostname to use for the OpenVPN server address.
      type: str
      returned: always
    verifyservercn:
      description: Verify the server certificate Common Name (CN) when the client
        connects.
      type: str
      returned: always
    blockoutsidedns:
      description: Block access to DNS servers except across OpenVPN while connected,
        forcing clients to use only VPN DNS servers.
      type: bool
      returned: always
    legacy:
      description: Do not include OpenVPN 2.5 and later settings in the client configuration.
      type: bool
      returned: always
    silent:
      description: Create Windows installer for unattended deploy.
      type: bool
      returned: always
    bindmode:
      description: The port binding mode to use. If OpenVPN client binds to the default
        OpenVPN port (1194), two clients may not run concurrently.
      type: str
      returned: always
    usepkcs11:
      description: Use PKCS#11 storage device (cryptographic token, HSM, smart card)
        instead of local files.
      type: bool
      returned: always
    pkcs11providers:
      description: The client local path to the PKCS#11 provider(s) (DLL, module)
      type: list
      returned: always
      elements: str
    pkcs11id:
      description: The object's ID on the PKCS#11 device.
      type: str
      returned: always
    usetoken:
      description: Use Microsoft Certificate Storage instead of local files.
      type: bool
      returned: always
    usepass:
      description: Use a password to protect the PKCS#12 file contents or key in Viscosity
        bundles.
      type: bool
      returned: always
    pass:
      description: Password used to protect the certificate file contents.
      type: str
      returned: always
    p12encryption:
      description: The level of encryption to use when exporting a PKCS#12 archive.
        Encryption support varies by Operating System and program
      type: str
      returned: always
    useproxy:
      description: Use proxy to communicate with the OpenVPN server.
      type: bool
      returned: always
    useproxytype:
      description: The proxy type to use.
      type: str
      returned: always
    proxyaddr:
      description: The IP address or hostname of the proxy server to use.
      type: str
      returned: always
    proxyport:
      description: 'The port where the proxy server is listening. Valid options are:
        a TCP/UDP port number'
      type: str
      returned: always
    useproxypass:
      description: The type of authentication to use for the proxy server.
      type: str
      returned: always
    proxyuser:
      description: The username to use to authenticate with the proxy server.
      type: str
      returned: always
    proxypass:
      description: The password to use to authenticate with the proxy server.
      type: str
      returned: always
    advancedoptions:
      description: Additional options to add to the OpenVPN client export configuration.
      type: str
      returned: always

"""


def run_module():
    """Runs this info module against /api/v2/vpn/openvpn/client_export/configs."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "query_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/vpn/openvpn/client_export/configs", client)
    changed = False
    resp = base_module.lookup_objects(lookup_params=module.params["query_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
