#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/vpn/wireguard/peers."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: vpn_wireguard_peers
description:
- Manage all WireGuard Peers.
short_description: Manage all WireGuard Peers.
requirements:
- pfSense-pkg-RESTAPI must be installed on the target system.
- pfSense-pkg-WireGuard must be installed on the target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  objects:
    type: list
    elements: dict
    required: true
    suboptions:
      enabled:
        required: false
        type: bool
        default: false
        choices: []
        description: Enables or disables this WireGuard peer.
      tun:
        required: false
        type: str
        default: unassigned
        choices: []
        description: The WireGuard tunnel for this peer.
      endpoint:
        required: false
        type: str
        default: null
        choices: []
        description: The IP address or hostname of the remote peer. Set to `null`
          to make this a dynamic endpoint.
      port:
        required: false
        type: str
        choices: []
        description: 'The port used by the remote peer. Valid options are: a TCP/UDP
          port number'
      descr:
        required: false
        type: str
        default: ''
        choices: []
        description: The description for this peer.
      persistentkeepalive:
        required: false
        type: int
        default: null
        choices: []
        description: The interval (in seconds) for Keep Alive packets sent to this
          peer. Set to `null` to disable.
      publickey:
        required: true
        type: str
        choices: []
        description: The public key for this peer.
      presharedkey:
        required: false
        type: str
        default: ''
        choices: []
        description: The pre-shared key for this tunnel.
      allowedips:
        required: false
        type: list
        default: []
        choices: []
        description: The allowed IP/subnets for this WireGuard peer.
        elements: dict
        suboptions:
          address:
            required: true
            type: str
            choices: []
            description: The IPv4 or IPv6 address for this peer IP.
          mask:
            required: true
            type: int
            choices: []
            description: The subnet mask for this peer IP.
          descr:
            required: false
            type: str
            default: ''
            choices: []
            description: A description for this allowed peer IP.
    description: The list of items to manage in the collection. Each item should be
      a dictionary representing the desired state of a single resource within the
      collection.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Manage all WireGuard Peers
  pfrest.pfsense.vpn_wireguard_peers:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    objects:
    - publickey: string
      enabled: false
      tun: unassigned

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: A list of WireGuard Peers returned by the API.
  type: list
  elements: dict
  returned: always
  contains:
    enabled:
      description: Enables or disables this WireGuard peer.
      type: bool
      returned: always
    tun:
      description: The WireGuard tunnel for this peer.
      type: str
      returned: always
    endpoint:
      description: The IP address or hostname of the remote peer. Set to `null` to
        make this a dynamic endpoint.
      type: str
      returned: always
    port:
      description: 'The port used by the remote peer. Valid options are: a TCP/UDP
        port number'
      type: str
      returned: always
    descr:
      description: The description for this peer.
      type: str
      returned: always
    persistentkeepalive:
      description: The interval (in seconds) for Keep Alive packets sent to this peer.
        Set to `null` to disable.
      type: int
      returned: always
    publickey:
      description: The public key for this peer.
      type: str
      returned: always
    allowedips:
      description: The allowed IP/subnets for this WireGuard peer.
      type: list
      returned: always
      elements: dict
      contains:
        address:
          description: The IPv4 or IPv6 address for this peer IP.
          type: str
          returned: always
        mask:
          description: The subnet mask for this peer IP.
          type: int
          returned: always
        descr:
          description: A description for this allowed peer IP.
          type: str
          returned: always

"""


def run_module():
    """Runs this collection module against /api/v2/vpn/wireguard/peers."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "objects": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "dict",
            "options": {
                "enabled": {
                    "type": "bool",
                    "required": False,
                    "no_log": False,
                    "default": False,
                    "nullable": True,
                },
                "tun": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "unassigned",
                    "nullable": True,
                },
                "endpoint": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": None,
                    "nullable": True,
                },
                "port": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "nullable": True,
                },
                "descr": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "",
                    "nullable": True,
                },
                "persistentkeepalive": {
                    "type": "int",
                    "required": False,
                    "no_log": False,
                    "default": None,
                    "nullable": True,
                },
                "publickey": {
                    "type": "str",
                    "required": True,
                    "no_log": False,
                    "nullable": False,
                },
                "presharedkey": {
                    "type": "str",
                    "required": False,
                    "no_log": False,
                    "default": "",
                    "nullable": True,
                },
                "allowedips": {
                    "type": "list",
                    "required": False,
                    "no_log": False,
                    "default": [],
                    "elements": "dict",
                    "nullable": True,
                    "options": {
                        "address": {
                            "type": "str",
                            "required": True,
                            "no_log": False,
                            "nullable": False,
                        },
                        "mask": {
                            "type": "int",
                            "required": True,
                            "no_log": False,
                            "nullable": False,
                        },
                        "descr": {
                            "type": "str",
                            "required": False,
                            "no_log": False,
                            "default": "",
                            "nullable": True,
                        },
                    },
                },
            },
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/vpn/wireguard/peers", client)
    changed, resp = base_module.replace_objects(
        data=module.params["objects"],
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
