#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/vpn/ipsec/phase2."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: vpn_ipsec_phase2
description:
- Manage individual IPsec Phase 2s.
short_description: Manage individual IPsec Phase 2s.
requirements:
- pfSense package L(pfSense-pkg-RESTAPI,https://pfrest.org) must be installed on the
  target system.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_protocol:
    type: str
    default: https
    choices:
    - http
    - https
    description: The protocol to use when connecting to the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  state:
    type: str
    choices:
    - present
    - absent
    default: present
    description: Whether the resource should be present or absent.
  lookup_fields:
    type: list
    elements: str
    required: true
    description: The list of fields to use when looking up existing resources. This
      should be a list of field names that uniquely identify a resource.
  ikeid:
    required: true
    type: int
    default: null
    choices: []
    description: The `ikeid` of the parent IPsec phase 1 entry this IPsec phase 2
      entry belongs to.
  descr:
    required: false
    type: str
    default: ''
    choices: []
    description: A description for this IPsec phase 2 entry.
  disabled:
    required: false
    type: bool
    default: false
    choices: []
    description: Disables this IPsec phase 2 entry.
  mode:
    required: true
    type: str
    default: null
    choices:
    - tunnel
    - tunnel6
    - transport
    - vti
    description: The IPsec phase 2 mode this entry will use.
  localid_type:
    required: false
    type: str
    default: null
    choices: []
    description: 'The local ID type to use for this phase 2 entry. Valid value options
      are: an existing interface, `address`, `network`. For interface values, the
      `:ip` modifier can be appended to the value to use the interface''s IP address
      instead of its entire subnet.'
  localid_address:
    required: false
    type: str
    default: null
    choices: []
    description: The local network IP component of this IPsec security association.
  localid_netbits:
    required: false
    type: int
    default: null
    choices: []
    description: The subnet bits of the `localid_address` network.
  natlocalid_type:
    required: false
    type: str
    default: null
    choices: []
    description: 'The NAT/BINAT translation type for this IPsec phase 2 entry. Leave
      as `null` if NAT/BINAT is not needed. Valid value options are: an existing interface,
      `address`, `network`. For interface values, the `:ip` modifier can be appended
      to the value to use the interface''s IP address instead of its entire subnet.'
  natlocalid_address:
    required: false
    type: str
    default: null
    choices: []
    description: The NAT/BINAT local network IP component of this IPsec security association.
  natlocalid_netbits:
    required: false
    type: int
    default: null
    choices: []
    description: The subnet bits of the `natlocalid_address` network.
  remoteid_type:
    required: false
    type: str
    default: null
    choices: []
    description: 'The remote ID type to use for this phase 2 entry. Valid value options
      are: `address`, `network`. For interface values, the `:ip` modifier can be appended
      to the value to use the interface''s IP address instead of its entire subnet.'
  remoteid_address:
    required: false
    type: str
    default: null
    choices: []
    description: The remote network IP component of this IPsec security association.
  remoteid_netbits:
    required: false
    type: int
    default: null
    choices: []
    description: The subnet bits of the `remoteid_address` network.
  protocol:
    required: false
    type: str
    default: esp
    choices:
    - esp
    - ah
    description: the IPsec phase 2 proposal protocol for this entry. Encapsulating
      Security Payload (`esp`) performs encryption and authentication, Authentication
      Header (`ah`) is authentication only.
  encryption_algorithm_option:
    required: false
    type: list
    default: null
    choices: []
    description: The encryption algorithms to be used by this phase 2 entry.
    elements: dict
    suboptions:
      name:
        required: true
        type: str
        default: null
        choices:
        - aes
        - aes128gcm
        - aes192gcm
        - aes256gcm
        - chacha20poly1305
        description: The name of the encryption algorithm to use for this P2 encryption
          item.
      keylen:
        required: false
        type: int
        default: null
        choices: []
        description: The key length for the encryption algorithm.
  hash_algorithm_option:
    required: true
    type: list
    default: null
    choices:
    - hmac_sha1
    - hmac_sha256
    - hmac_sha384
    - hmac_sha512
    - aesxcbc
    description: 'The hashing algorithms used by this IPsec phase 2 entry. Note: Hash
      is ignored with GCM algorithms. SHA1 provides weak security and should be avoided.'
    elements: str
  pfsgroup:
    required: false
    type: int
    default: 14
    choices:
    - 0
    - 1
    - 2
    - 5
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    description: 'The PFS key group this IPsec phase 2 entry should use. Note: Groups
      1, 2, 5, 22, 23, and 24 provide weak security and should be avoided.'
  rekey_time:
    required: false
    type: int
    default: 3240
    choices: []
    description: The amount of time (in seconds) before an IKE SA establishes new
      keys.
  rand_time:
    required: false
    type: int
    default: 360
    choices: []
    description: A random value up to this amount will be subtracted from the `rekey_time`
      and `reauth_time` to avoid simultaneous renegotiation.
  lifetime:
    required: false
    type: int
    default: 3600
    choices: []
    description: The hard IKE SA lifetime (in seconds) after which the IKE SA will
      be expired.
  pinghost:
    required: false
    type: str
    default: ''
    choices: []
    description: The IP address to send an ICMP echo request to inside the tunnel.
      Can trigger initiation of a tunnel mode P2, but does not trigger initiation
      of a VTI mode P2.
  keepalive:
    required: false
    type: bool
    default: false
    choices: []
    description: Enables or disables checking this P2 and initiating if disconnected;
      does not send traffic inside the tunnel. This check ignores the P1 option 'Child
      SA Start Action' and works for both VTI and tunnel mode P2s. For IKEv2 without
      split connections, this only needs to be enabled on one P2.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Create IPsec Phase 2
  pfrest.pfsense.vpn_ipsec_phase2:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: present
    ikeid: 1
    mode: tunnel
    localid_type: string
    localid_address: string
    localid_netbits: 1
    natlocalid_address: string
    natlocalid_netbits: 1
    remoteid_type: string
    remoteid_address: string
    remoteid_netbits: 1
    encryption_algorithm_option: &id001
    - name: aes
      keylen: 1
    hash_algorithm_option: &id002
    - hmac_sha1
- name: Delete IPsec Phase 2
  pfrest.pfsense.vpn_ipsec_phase2:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    state: absent
    ikeid: 1
    mode: tunnel
    localid_type: string
    localid_address: string
    localid_netbits: 1
    natlocalid_address: string
    natlocalid_netbits: 1
    remoteid_type: string
    remoteid_address: string
    remoteid_netbits: 1
    encryption_algorithm_option: *id001
    hash_algorithm_option: *id002

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The IPsec Phase 2 data returned by the API.
  type: dict
  returned: always
  contains:
    uniqid:
      description: A unique ID used to identify this IPsec phase2 entry internally.
        This value is automatically set by the system and cannot be changed.
      type: str
      returned: always
    reqid:
      description: A unique ID used to identify this IPsec phase2 entry internally.
        This value is automatically set by the system and cannot be changed.
      type: int
      returned: always
    ikeid:
      description: The `ikeid` of the parent IPsec phase 1 entry this IPsec phase
        2 entry belongs to.
      type: int
      returned: always
    descr:
      description: A description for this IPsec phase 2 entry.
      type: str
      returned: always
    disabled:
      description: Disables this IPsec phase 2 entry.
      type: bool
      returned: always
    mode:
      description: The IPsec phase 2 mode this entry will use.
      type: str
      returned: always
    localid_type:
      description: 'The local ID type to use for this phase 2 entry. Valid value options
        are: an existing interface, `address`, `network`. For interface values, the
        `:ip` modifier can be appended to the value to use the interface''s IP address
        instead of its entire subnet.'
      type: str
      returned: always
    localid_address:
      description: The local network IP component of this IPsec security association.
      type: str
      returned: always
    localid_netbits:
      description: The subnet bits of the `localid_address` network.
      type: int
      returned: always
    natlocalid_type:
      description: 'The NAT/BINAT translation type for this IPsec phase 2 entry. Leave
        as `null` if NAT/BINAT is not needed. Valid value options are: an existing
        interface, `address`, `network`. For interface values, the `:ip` modifier
        can be appended to the value to use the interface''s IP address instead of
        its entire subnet.'
      type: str
      returned: always
    natlocalid_address:
      description: The NAT/BINAT local network IP component of this IPsec security
        association.
      type: str
      returned: always
    natlocalid_netbits:
      description: The subnet bits of the `natlocalid_address` network.
      type: int
      returned: always
    remoteid_type:
      description: 'The remote ID type to use for this phase 2 entry. Valid value
        options are: `address`, `network`. For interface values, the `:ip` modifier
        can be appended to the value to use the interface''s IP address instead of
        its entire subnet.'
      type: str
      returned: always
    remoteid_address:
      description: The remote network IP component of this IPsec security association.
      type: str
      returned: always
    remoteid_netbits:
      description: The subnet bits of the `remoteid_address` network.
      type: int
      returned: always
    protocol:
      description: the IPsec phase 2 proposal protocol for this entry. Encapsulating
        Security Payload (`esp`) performs encryption and authentication, Authentication
        Header (`ah`) is authentication only.
      type: str
      returned: always
    encryption_algorithm_option:
      description: The encryption algorithms to be used by this phase 2 entry.
      type: list
      returned: always
      elements: dict
      contains:
        name:
          description: The name of the encryption algorithm to use for this P2 encryption
            item.
          type: str
          returned: always
        keylen:
          description: The key length for the encryption algorithm.
          type: int
          returned: always
    hash_algorithm_option:
      description: 'The hashing algorithms used by this IPsec phase 2 entry. Note:
        Hash is ignored with GCM algorithms. SHA1 provides weak security and should
        be avoided.'
      type: list
      returned: always
      elements: str
    pfsgroup:
      description: 'The PFS key group this IPsec phase 2 entry should use. Note: Groups
        1, 2, 5, 22, 23, and 24 provide weak security and should be avoided.'
      type: int
      returned: always
    rekey_time:
      description: The amount of time (in seconds) before an IKE SA establishes new
        keys.
      type: int
      returned: always
    rand_time:
      description: A random value up to this amount will be subtracted from the `rekey_time`
        and `reauth_time` to avoid simultaneous renegotiation.
      type: int
      returned: always
    lifetime:
      description: The hard IKE SA lifetime (in seconds) after which the IKE SA will
        be expired.
      type: int
      returned: always
    pinghost:
      description: The IP address to send an ICMP echo request to inside the tunnel.
        Can trigger initiation of a tunnel mode P2, but does not trigger initiation
        of a VTI mode P2.
      type: str
      returned: always
    keepalive:
      description: Enables or disables checking this P2 and initiating if disconnected;
        does not send traffic inside the tunnel. This check ignores the P1 option
        'Child SA Start Action' and works for both VTI and tunnel mode P2s. For IKEv2
        without split connections, this only needs to be enabled on one P2.
      type: bool
      returned: always

"""


def run_module():
    """Runs this resource module against /api/v2/vpn/ipsec/phase2."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "https",
            "choices": ["http", "https"],
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "state": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "present",
            "choices": ["present", "absent"],
        },
        "lookup_fields": {
            "type": "list",
            "required": True,
            "no_log": False,
            "elements": "str",
        },
        "ikeid": {
            "type": "int",
            "required": True,
            "no_log": False,
            "default": None,
            "nullable": False,
        },
        "descr": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
            "nullable": True,
        },
        "disabled": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
        "mode": {
            "type": "str",
            "required": True,
            "no_log": False,
            "default": None,
            "choices": ["tunnel", "tunnel6", "transport", "vti"],
            "nullable": False,
        },
        "localid_type": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "localid_address": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "localid_netbits": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "natlocalid_type": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "natlocalid_address": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "natlocalid_netbits": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "remoteid_type": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "remoteid_address": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "remoteid_netbits": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": None,
            "nullable": True,
        },
        "protocol": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "esp",
            "choices": ["esp", "ah"],
            "nullable": True,
        },
        "encryption_algorithm_option": {
            "type": "list",
            "required": False,
            "no_log": False,
            "default": None,
            "elements": "dict",
            "nullable": True,
            "options": {
                "name": {
                    "type": "str",
                    "required": True,
                    "no_log": False,
                    "default": None,
                    "choices": [
                        "aes",
                        "aes128gcm",
                        "aes192gcm",
                        "aes256gcm",
                        "chacha20poly1305",
                    ],
                    "nullable": False,
                },
                "keylen": {
                    "type": "int",
                    "required": False,
                    "no_log": False,
                    "default": None,
                    "nullable": True,
                },
            },
        },
        "hash_algorithm_option": {
            "type": "list",
            "required": True,
            "no_log": False,
            "default": None,
            "choices": [
                "hmac_sha1",
                "hmac_sha256",
                "hmac_sha384",
                "hmac_sha512",
                "aesxcbc",
            ],
            "elements": "str",
            "nullable": False,
        },
        "pfsgroup": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 14,
            "choices": [
                0,
                1,
                2,
                5,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
            ],
            "nullable": True,
        },
        "rekey_time": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 3240,
            "nullable": True,
        },
        "rand_time": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 360,
            "nullable": True,
        },
        "lifetime": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 3600,
            "nullable": True,
        },
        "pinghost": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "",
            "nullable": True,
        },
        "keepalive": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": False,
            "nullable": True,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        scheme=module.params["api_protocol"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params.get("api_key", ""),
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/vpn/ipsec/phase2", client)
    changed, resp = base_module.set_object_state(
        state=module.params["state"],
        data=module.params,
        lookup_fields=module.params["lookup_fields"],
        parent_lookup_query=module.params.get("parent_lookup_query"),
    )

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
