#!/usr/bin/python
###############################################################
# DO NOT EDIT THIS FILE DIRECTLY. THIS FILE IS AUTO-GENERATED.
# BY tools/module_generator.py BASED ON THE REST API SCHEMA IF
# YOU NEED TO MAKE CHANGES, PLEASE EDIT THE TEMPLATE OR THE
# GENERATOR SCRIPT. ALTERNATIVELY, YOU CAN OVERRIDE THE AUTO
# GENERATED MODULE BY ADDING THIS MODULES NAME TO THE
# tools/generator.yml FILE.
###############################################################
"""An Ansible module for interacting with /api/v2/vpn/openvpn/cso."""

# pylint: disable=too-many-lines,duplicate-code

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.pfrest.pfsense.plugins.module_utils import base, rest

DOCUMENTATION = r"""
module: vpn_openvpn_cso_info
description:
- Retrieve information about a single Open VPN Client Specific Override.
short_description: Retrieve information about a single Open VPN Client Specific Override.
options:
  api_host:
    type: str
    required: true
    description: The hostname or IP address of the pfSense device.
  api_port:
    type: int
    default: 443
    description: The port number of the pfSense API.
  api_username:
    type: str
    default: admin
    description: The username to authenticate with the pfSense API.
  api_password:
    type: str
    default: pfsense
    description: The password to authenticate with the pfSense API.
  api_key:
    type: str
    description: An API key to use for authentication.
  validate_certs:
    type: bool
    default: true
    description: Whether to validate SSL certificates when connecting to the API.
  lookup_params:
    type: dict
    description: Parameters to lookup the specific resource to retrieve.
author:
- Jared Hendrickson (@jaredhendrickson13)

"""

EXAMPLES = """
- name: Retrieve Open VPN Client Specific Override
  pfrest.pfsense.vpn_openvpn_cso_info:
    api_host: pfsense.example.com
    api_username: admin
    api_password: pfsense
    lookup_params: {}

"""

RETURN = """
changed:
  description: Whether any changes were made.
  type: bool
  returned: always
status:
  description: The HTTP status code of the API response.
  type: int
  returned: always
response_id:
  description: The unique response/error ID from the API.
  type: str
  returned: always
msg:
  description: A status message from the API.
  type: str
  returned: always
data:
  description: The Open VPN Client Specific Override data returned by the API.
  type: dict
  returned: always
  contains:
    common_name:
      description: The X.509 common name for the client certificate, or the username
        for VPNs utilizing password authentication.
      type: str
      returned: always
    disable:
      description: Disables this client specific override.
      type: bool
      returned: always
    block:
      description: Enables or disables the client from connecting to this server.
        Do not use this option to permanently disable a client due to a compromised
        key or password. Use a CRL instead.
      type: bool
      returned: always
    description:
      description: The description for this client specific override.
      type: str
      returned: always
    server_list:
      description: The OpenVPN servers that will utilize this override. When no servers
        are specified, the override will apply to all servers.
      type: list
      returned: always
      elements: str
    tunnel_network:
      description: The IPv4 virtual network used for private communications between
        the server and client hosts.
      type: str
      returned: always
    tunnel_networkv6:
      description: The IPv6 virtual network used for private communications between
        the server and client hosts.
      type: str
      returned: always
    local_network:
      description: The IPv4 server-side networks that will be accessible from this
        particular client.
      type: list
      returned: always
      elements: str
    local_networkv6:
      description: the IPv6 server-side networks that will be accessible from this
        particular client.
      type: list
      returned: always
      elements: str
    remote_network:
      description: The IPv4 client-side networks that will be routed to this client
        specifically using iroute, so that a site-to-site VPN can be established.
      type: list
      returned: always
      elements: str
    remote_networkv6:
      description: The IPv6 client-side networks that will be routed to this client
        specifically using iroute, so that a site-to-site VPN can be established.
      type: list
      returned: always
      elements: str
    gwredir:
      description: Enable forcing all client-generated traffic through the tunnel.
      type: bool
      returned: always
    push_reset:
      description: Enables or disables preventing this client from receiving any server-defined
        client settings.
      type: bool
      returned: always
    remove_options:
      description: Specifies the push-remove options to apply to the client
      type: list
      returned: always
      elements: str
    dns_domain:
      description: The default domain to provide to the client.
      type: str
      returned: always
    dns_server1:
      description: The primary DNS server to provide to the client.
      type: str
      returned: always
    dns_server2:
      description: The secondary DNS server to provide to the client.
      type: str
      returned: always
    dns_server3:
      description: The tertiary DNS server to provide to the client.
      type: str
      returned: always
    dns_server4:
      description: The quaternary DNS server to provide to the client.
      type: str
      returned: always
    ntp_server1:
      description: The primary NTP server to provide to the client.
      type: str
      returned: always
    ntp_server2:
      description: The secondary NTP server to provide to the client.
      type: str
      returned: always
    netbios_enable:
      description: Enables or disables NetBIOS over TCP/IP.
      type: bool
      returned: always
    netbios_ntype:
      description: The NetBIOS node type.
      type: int
      returned: always
    netbios_scope:
      description: The NetBIOS Scope ID. This provides an extended naming service
        for NetBIOS over TCP/IP. The NetBIOS scope ID isolates NetBIOS traffic on
        a single network to only those nodes with the same NetBIOS scope ID.
      type: str
      returned: always
    wins_server1:
      description: The primary WINS server to provide to the client.
      type: str
      returned: always
    wins_server2:
      description: The secondary WINS server to provide to the client.
      type: str
      returned: always
    custom_options:
      description: Additional OpenVPN options to add for this client.
      type: list
      returned: always
      elements: str

"""


def run_module():
    """Runs this info module against /api/v2/vpn/openvpn/cso."""

    module_args = {
        "api_host": {
            "type": "str",
            "required": True,
            "no_log": False,
        },
        "api_port": {
            "type": "int",
            "required": False,
            "no_log": False,
            "default": 443,
        },
        "api_username": {
            "type": "str",
            "required": False,
            "no_log": False,
            "default": "admin",
        },
        "api_password": {
            "type": "str",
            "required": False,
            "no_log": True,
            "default": "pfsense",
        },
        "api_key": {
            "type": "str",
            "required": False,
            "no_log": True,
        },
        "validate_certs": {
            "type": "bool",
            "required": False,
            "no_log": False,
            "default": True,
        },
        "lookup_params": {
            "type": "dict",
            "required": False,
            "no_log": False,
        },
    }

    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    client = rest.RestClient(
        host=module.params["api_host"],
        port=module.params["api_port"],
        username=module.params["api_username"],
        password=module.params["api_password"],
        api_key=module.params["api_key"],
        validate_certs=module.params["validate_certs"],
    )

    base_module = base.BaseModule("/api/v2/vpn/openvpn/cso", client)
    changed = False
    resp = base_module.lookup_object(lookup_params=module.params["lookup_params"])

    # Capture the response message and clear it (prevent duplicate message/msg in result)
    message = resp.get("message", "")
    if "message" in resp:
        del resp["message"]

    # If the result was unsuccessful, fail the tasks with the error message returned from the API
    if "code" not in resp or resp["code"] != 200:
        module.fail_json(msg=message, **resp)

    result = {"changed": changed, "msg": "Successfully completed API request.", **resp}
    module.exit_json(**result)


if __name__ == "__main__":
    run_module()
